"""Banco de respuestas reales del HUS — few-shots por familia de glosa.

Aportado por el dueño el 16-jun-2026: 8 familias (AU, TA, SO, CL, ME, IN,
CO, FA) con 3 respuestas tipo cada una, escritas por el equipo de cartera
del HUS. Estilo característico:
  • Apertura "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE…"
  • Cita normativa con número exacto (Ley 1751/2015, Resolución 2335/2023,
    Decreto 780/2016)
  • Tono firme, terminología jurídico-médica precisa
  • Cierre exigiendo el levantamiento total + pago inmediato

REGLA del dueño: estas respuestas son GENÉRICAS — la IA las usa como
**punto de partida** para construir el dictamen final más técnico y
pulido con los datos REALES del caso. NO las copia literal.

El bloque se inyecta al user prompt cuando se detecta la familia. El
modelo entiende: "así escribe el HUS — adapta el patrón con los datos
del caso concreto".
"""

from __future__ import annotations

# ── 8 familias × 3 ejemplos = 24 respuestas modelo del HUS ──────────
BANCO_HUS: dict[str, tuple[str, ...]] = {
    "AU": (
        # 1) Falta autorización previa por urgencia vital
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE FALTA DE AUTORIZACIÓN PREVIA "
        "PARA LA ATENCIÓN, TODA VEZ QUE LA PRESTACIÓN DEL SERVICIO CORRESPONDE "
        "A UNA URGENCIA VITAL INMINENTE, AMPARADA BAJO EL ARTÍCULO 14 DE LA "
        "LEY ESTATUTARIA 1751 DE 2015 Y EL DECRETO 780 DE 2016. ESTA "
        "NORMATIVIDAD PROHÍBE EXPRESAMENTE A LAS ENTIDADES RESPONSABLES DE "
        "PAGO EXIGIR AUTORIZACIONES PREVIAS O CUALQUIER TIPO DE TRÁMITE "
        "ADMINISTRATIVO QUE CONSTITUYA UNA BARRERA DE ACCESO PARA LA "
        "ATENCIÓN DE URGENCIAS. EL PACIENTE INGRESÓ CON UN CUADRO CLÍNICO "
        "CRÍTICO QUE COMPROMETÍA SU VIDA, REQUIRIENDO INTERVENCIÓN MÉDICA "
        "INMEDIATA EN NUESTRA INSTITUCIÓN DE ALTA COMPLEJIDAD. EN CONSECUENCIA, "
        "CONDICIONAR EL RECONOCIMIENTO ECONÓMICO DE ESTOS SERVICIOS A UN AVAL "
        "ADMINISTRATIVO NO SOLO ES UNA EXTRALIMITACIÓN ILEGAL, SINO QUE "
        "ATENTA DIRECTAMENTE CONTRA EL DERECHO FUNDAMENTAL A LA SALUD. SE "
        "EXIGE EL LEVANTAMIENTO TOTAL DE LA OBJECIÓN, APLICANDO EL PRINCIPIO "
        "PRO IPS Y LA BUENA FE CONTRACTUAL.",
        # 2) Autorización vencida / fuera de tiempos por factores clínicos
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE AUTORIZACIÓN VENCIDA O FUERA "
        "DE LOS TIEMPOS ESTABLECIDOS, DEBIDO A QUE LA SUPUESTA DEMORA EN LA "
        "PRESTACIÓN DEL SERVICIO OBEDECIÓ EXCLUSIVAMENTE A FACTORES CLÍNICOS, "
        "INESTABILIDAD HEMODINÁMICA Y CONDICIONES FISIOLÓGICAS DEL PACIENTE "
        "QUE OBLIGARON AL CUERPO MÉDICO A REPROGRAMAR EL PROCEDIMIENTO PARA "
        "GARANTIZAR SU SEGURIDAD VITAL. LA LEY ESTATUTARIA DE SALUD EN SU "
        "ARTÍCULO 8 GARANTIZA LA CONTINUIDAD E INTEGRALIDAD DEL TRATAMIENTO "
        "SIN BARRERAS ADMINISTRATIVAS. ES COMPLETAMENTE INACEPTABLE QUE LA "
        "EPS PRETENDA TRASLADAR EL RIESGO ADMINISTRATIVO DE SUS PROCESOS "
        "INTERNOS DE RENOVACIÓN DE AUTORIZACIONES A NUESTRO HOSPITAL, CUANDO "
        "LA ATENCIÓN FUE EFECTIVAMENTE PRESTADA Y ESTRICTAMENTE AVALADA POR "
        "EL ESPECIALISTA TRATANTE. SE SOLICITA EL LEVANTAMIENTO INMEDIATO DE "
        "ESTA GLOSA BASADO EN LA PREVALENCIA DEL ACTO MÉDICO Y LA PROTECCIÓN "
        "AL USUARIO.",
        # 3) Servicio derivado de urgencia inicial (principio de integralidad)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE SERVICIO NO AUTORIZADO "
        "ESPECÍFICAMENTE EN EL DOCUMENTO, YA QUE DICHO PROCEDIMIENTO SE "
        "DERIVÓ DIRECTAMENTE DE UNA ATENCIÓN DE URGENCIA INICIAL Y FORMA "
        "PARTE INDIVISIBLE DEL MANEJO INTEGRAL DEL PACIENTE. APLICANDO EL "
        "PRINCIPIO DE INTEGRALIDAD CONTEMPLADO EN LA JURISPRUDENCIA DE LA "
        "CORTE CONSTITUCIONAL Y EN LA LEY 1751 DE 2015, SE ENTIENDE QUE "
        "TODOS LOS SERVICIOS, TECNOLOGÍAS, MEDICAMENTOS E INSUMOS REQUERIDOS "
        "PARA RESOLVER LA CONDICIÓN DE SALUD DEL USUARIO DEBEN SER CUBIERTOS "
        "SIN FRACCIONAMIENTO. NUESTRA IPS RADICÓ OPORTUNAMENTE LOS ANEXOS "
        "TÉCNICOS CORRESPONDIENTES SOLICITANDO LOS SERVICIOS ADICIONALES A "
        "TRAVÉS DE LOS CANALES OFICIALES Y, ANTE EL SILENCIO ADMINISTRATIVO "
        "DE LA EPS EN LOS TIEMPOS DISPUESTOS POR LA RESOLUCIÓN 2284 DE 2023 "
        "Y LA RESOLUCIÓN 2335 DE 2023, ESTOS SE ENTIENDEN TÁCITAMENTE "
        "APROBADOS. PROCEDER CON LA GLOSA CARECE DE SUSTENTO LEGAL Y TÉCNICO.",
    ),
    "TA": (
        # 1) Cobro superior a tarifa pactada (defensa contractual)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE COBRO SUPERIOR A LA TARIFA "
        "PACTADA O MODIFICACIÓN UNILATERAL DE LOS VALORES, YA QUE EL VALOR "
        "FACTURADO CORRESPONDE EXACTAMENTE A LA TARIFA ACORDADA EN EL "
        "CONTRATO VIGENTE Y SUS RESPECTIVOS ANEXOS TÉCNICOS AL MOMENTO DE LA "
        "PRESTACIÓN EFECTIVA DEL SERVICIO. ES IMPERATIVO RECORDAR A LA "
        "ENTIDAD RESPONSABLE DE PAGO QUE LOS ACUERDOS DE VOLUNTADES TIENEN "
        "FUERZA VINCULANTE Y NO PUEDEN SER DESCONOCIDOS MEDIANTE GLOSAS "
        "TEMERARIAS QUE BUSCAN RETRASAR EL FLUJO DE RECURSOS. LA LIQUIDACIÓN "
        "FUE VERIFICADA POR NUESTRO DEPARTAMENTO DE AUDITORÍA FINANCIERA, "
        "CONFIRMANDO QUE SE APLICARON CORRECTAMENTE LOS PORCENTAJES DEL "
        "MANUAL TARIFARIO PACTADO (SEAN SALARIOS MÍNIMOS LEGALES O UVR). "
        "ACEPTAR ESTA GLOSA IMPLICARÍA UNA VIOLACIÓN AL PRINCIPIO DE LA BUENA "
        "FE CONTRACTUAL Y AL EQUILIBRIO ECONÓMICO DEL CONTRATO, POR LO QUE "
        "SE EXIGE EL LEVANTAMIENTO TOTAL Y EL PAGO INMEDIATO DE LOS SALDOS "
        "RETENIDOS INJUSTIFICADAMENTE.",
        # 2) Liquidación incorrecta quirúrgicos múltiples / bilaterales
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE LIQUIDACIÓN INCORRECTA DE "
        "PROCEDIMIENTOS QUIRÚRGICOS MÚLTIPLES O BILATERALES, PUES LA "
        "FACTURACIÓN SE REALIZÓ EN ESTRICTO APEGO A LAS VÍAS DE ACCESO, "
        "GRUPOS QUIRÚRGICOS Y PORCENTAJES ESTABLECIDOS EN EL MANUAL "
        "TARIFARIO PACTADO (SOAT O ISS 2001). AL REVISAR EL REGISTRO DE "
        "ANESTESIA Y LA DESCRIPCIÓN DEL CIRUJANO, SE COMPRUEBA QUE SE TRATÓ "
        "DE INTERVENCIONES COMPLEJAS REALIZADAS POR DIFERENTE VÍA DE ACCESO "
        "Y/O POR ESPECIALISTAS DE DIFERENTE DISCIPLINA EN EL MISMO ACTO "
        "QUIRÚRGICO. EL DESCUENTO APLICADO POR LA EPS ES ERRÓNEO Y "
        "DEMUESTRA UNA INTERPRETACIÓN SESGADA DE LOS CAPÍTULOS DE "
        "LIQUIDACIÓN QUIRÚRGICA DEL MANUAL. SE ANEXA NUEVAMENTE EL "
        "PROTOCOLO OPERATORIO QUE SOPORTA LA MAGNITUD DEL EVENTO, "
        "EXIGIENDO QUE SE REVISE TÉCNICAMENTE Y SE RECONOZCA EL 100% DEL "
        "VALOR FACTURADO POR HONORARIOS MÉDICOS, DERECHOS DE SALA Y "
        "MATERIALES SEGÚN LO ESTIPULA LA NORMATIVA APLICABLE.",
        # 3) Tarifa NO pactada para insumos / dispositivos de alto costo
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE TARIFA NO PACTADA PARA "
        "INSUMOS, DISPOSITIVOS O MEDICAMENTOS DE ALTO COSTO, YA QUE AL "
        "TRATARSE DE ELEMENTOS VITALES NO INCLUIDOS EN LA MATRIZ DE "
        "CONTRATACIÓN ORIGINAL, SE PROCEDIÓ A FACTURARLOS A PRECIO DE "
        "COMPRA MÁS EL PORCENTAJE DE INTERMEDIACIÓN ADMINISTRATIVA "
        "LOGÍSTICA ESTÁNDAR DEL SECTOR. ESTE PROCEDIMIENTO ES AMPARADO "
        "POR LOS LINEAMIENTOS DEL MINISTERIO DE SALUD CUANDO SE TRATA DE "
        "GARANTIZAR LA CONTINUIDAD EN LA PRESTACIÓN DEL SERVICIO Y "
        "SALVAGUARDAR LA VIDA DEL PACIENTE. NO ES JURÍDICAMENTE ACEPTABLE "
        "QUE LA EPS ESPERE QUE EL HOSPITAL UNIVERSITARIO DE SANTANDER "
        "ASUMA EL COSTO DEL MATERIAL NO CONTRATADO CUANDO EL BENEFICIARIO "
        "DIRECTO ES SU AFILIADO. SE ADJUNTAN LAS FACTURAS DE COMPRA AL "
        "PROVEEDOR QUE DEMUESTRAN LA TRANSPARENCIA DEL COBRO, POR LO QUE "
        "ESTA OBJECIÓN CARECE DE FUNDAMENTO FINANCIERO Y DEBE SER "
        "LEVANTADA EN SU TOTALIDAD A FAVOR DE NUESTRA IPS.",
    ),
    "SO": (
        # 1) Falta epicrisis / resumen de atención
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE FALTA DE EPICRISIS O "
        "RESUMEN DE ATENCIÓN EN LOS SOPORTES FÍSICOS O DIGITALES, TODA VEZ "
        "QUE EN EL EXPEDIENTE ENVIADO Y AVALADO MEDIANTE EL CÓDIGO ÚNICO DE "
        "VALIDACIÓN (CUV) SE ENCUENTRA LA TOTALIDAD DEL REGISTRO CLÍNICO Y "
        "LAS NOTAS DE EVOLUCIÓN QUE CUMPLEN A CABALIDAD CON LOS REQUISITOS "
        "ESTABLECIDOS EN LA RESOLUCIÓN 1995 DE 1999 Y LA RESOLUCIÓN 2335 "
        "DE 2023. EL COMPENDIO DOCUMENTAL APORTADO INCLUYE DIAGNÓSTICOS, "
        "TRATAMIENTOS, PROCEDIMIENTOS Y EL DESENLACE DEL PACIENTE, SIENDO "
        "UN DOCUMENTO PLENAMENTE VÁLIDO PARA COMPROBAR LA PRESTACIÓN "
        "EFECTIVA DEL SERVICIO. LA EPS NO PUEDE ESCUDARSE EN SUPUESTAS "
        "CARENCIAS DOCUMENTALES CUANDO LA PLATAFORMA DE INTEROPERABILIDAD "
        "REGISTRÓ LA RECEPCIÓN EXITOSA DE LOS ARCHIVOS PLANOS Y LOS "
        "SOPORTES PDF. SE RATIFICA LA PERTINENCIA DEL COBRO Y SE EXIGE LA "
        "CANCELACIÓN INMEDIATA DEL VALOR OBJETADO BAJO LA PREMISA DE LA "
        "VERDAD SABIDA Y LA BUENA FE.",
        # 2) Ausencia de copias de documento de identidad
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE AUSENCIA DE COPIAS DE "
        "DOCUMENTOS DE IDENTIDAD DEL PACIENTE (CÉDULA, TARJETA DE IDENTIDAD "
        "O REGISTRO CIVIL), YA QUE LA RESOLUCIÓN 2335 DE 2023 PROHÍBE "
        "EXPRESAMENTE A LAS ENTIDADES RESPONSABLES DE PAGO EXIGIR COPIAS "
        "FÍSICAS O DIGITALES DE DOCUMENTOS QUE PUEDEN VERIFICARSE "
        "DIRECTAMENTE EN LAS BASES DE DATOS DEL ESTADO, TALES COMO LA BDUA "
        "Y EL SISTEMA ADRES. EL PACIENTE FUE IDENTIFICADO BIOMÉTRICAMENTE Y "
        "SUS DATOS FUERON VALIDADOS EN EL SISTEMA DE AFILIACIÓN "
        "TRANSACCIONAL AL MOMENTO DEL INGRESO. SOLICITAR ESTE TIPO DE "
        "SOPORTES OBSOLETOS CONSTITUYE UNA PRÁCTICA DILATORIA SANCIONADA "
        "POR LA SUPERINTENDENCIA NACIONAL DE SALUD MEDIANTE SU CIRCULAR "
        "ÚNICA. EL HOSPITAL UNIVERSITARIO DE SANTANDER CUMPLIÓ CON SU "
        "OBLIGACIÓN ASISTENCIAL Y DE IDENTIFICACIÓN, POR LO TANTO, ESTA "
        "GLOSA ES TOTALMENTE IMPROCEDENTE Y DEBE SER LEVANTADA DE INMEDIATO.",
        # 3) Falta firma del paciente por imposibilidad clínica
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE FALTA DE FIRMA DEL "
        "PACIENTE EN EL PAGARÉ, CONSENTIMIENTO INFORMADO O COMPROBANTE DE "
        "RECIBO DE SERVICIOS, DEBIDO A QUE EL ESTADO CLÍNICO DE ALTERACIÓN "
        "DE CONCIENCIA, SEDACIÓN PROFUNDA O GRAVEDAD INMINENTE DEL MISMO "
        "IMPEDÍA MATERIALMENTE ESTE TRÁMITE ADMINISTRATIVO. COMO PRESTADOR "
        "DE ALTA COMPLEJIDAD, NUESTRA PRIORIDAD ABSOLUTA FUE LA PRESTACIÓN "
        "DE LA ASISTENCIA VITAL, AMPARADA BAJO EL PRINCIPIO DEL ESTADO DE "
        "NECESIDAD Y LA ÉTICA MÉDICA. EL REGISTRO DE TRIAGE Y LAS NOTAS DE "
        "ENFERMERÍA CERTIFICAN LAS CONDICIONES DE RECEPCIÓN DEL USUARIO Y "
        "LA IMPOSIBILIDAD DE RECAUDAR FIRMAS. EXIGIR ESTE REQUISITO BAJO "
        "CONDICIONES CLÍNICAS CRÍTICAS CARECE DE LÓGICA Y EMPATÍA, "
        "VIOLANDO DIRECTAMENTE LOS PRINCIPIOS DE ACCESIBILIDAD Y "
        "OPORTUNIDAD ESTIPULADOS EN LA LEY 100 DE 1993 Y SUS DECRETOS "
        "REGLAMENTARIOS, LO CUAL EXIGE EL LEVANTAMIENTO TOTAL DE LA "
        "RETENCIÓN FINANCIERA.",
    ),
    "CL": (
        # 1) Estancia injustificada / días adicionales
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE ESTANCIA INJUSTIFICADA O "
        "DÍAS ADICIONALES DE HOSPITALIZACIÓN, YA QUE LAS NOTAS DE EVOLUCIÓN "
        "DIARIA DEMUESTRAN CLARAMENTE QUE EL PACIENTE PRESENTABA "
        "INESTABILIDAD HEMODINÁMICA, ALTERACIONES EN LOS PARÁMETROS DE "
        "LABORATORIO Y ALTO RIESGO DE COMPLICACIONES POSTOPERATORIAS QUE "
        "HACÍAN IMPERATIVO MANTENERLO BAJO OBSERVACIÓN MÉDICA "
        "INTRAHOSPITALARIA DE MANERA CONTINUA. DAR DE ALTA DE FORMA "
        "PREMATURA A UN USUARIO EN ESTAS CONDICIONES HABRÍA SIGNIFICADO "
        "NEGLIGENCIA MÉDICA Y UN PELIGRO INMINENTE PARA SU VIDA, LO CUAL VA "
        "EN CONTRA DE LOS PROTOCOLOS DE SEGURIDAD DEL PACIENTE DE NUESTRA "
        "INSTITUCIÓN. LA DECISIÓN DE PROLONGAR LA ESTANCIA FUE ESTRICTAMENTE "
        "BASADA EN EL CRITERIO DEL ESPECIALISTA TRATANTE Y SOPORTADA EN "
        "GUÍAS DE PRÁCTICA CLÍNICA BASADAS EN EVIDENCIA, HACIENDO QUE ESTA "
        "OBJECIÓN SEA TÉCNICAMENTE INVIABLE Y DEBA SER REVERTIDA A FAVOR "
        "DEL HOSPITAL.",
        # 2) Procedimiento NO pertinente / exámenes innecesarios
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE PROCEDIMIENTO NO "
        "PERTINENTE O EXÁMENES DE LABORATORIO INNECESARIOS, TODA VEZ QUE "
        "DICHAS INTERVENCIONES FUERON ORDENADAS BAJO LA ESTRICTA AUTONOMÍA "
        "MÉDICA DEL ESPECIALISTA, RESPALDADA POR EL ARTÍCULO 17 DE LA LEY "
        "ESTATUTARIA 1751 DE 2015. ESTAS PRUEBAS FUERON CRUCIALES PARA EL "
        "DIAGNÓSTICO DIFERENCIAL, EL DESCARTE DE PATOLOGÍAS DE ALTO RIESGO "
        "CONCOMITANTES Y LA DEFINICIÓN DEL ABORDAJE TERAPÉUTICO ADECUADO. "
        "UN AUDITOR DE ESCRITORIO DE LA EPS NO PUEDE DESCONOCER LA "
        "DINÁMICA CLÍNICA DE UN PACIENTE EN TIEMPO REAL NI PRETENDER "
        "RESTRINGIR EL ARSENAL DIAGNÓSTICO NECESARIO PARA GARANTIZAR UNA "
        "ATENCIÓN SEGURA. LA PERTINENCIA ESTÁ ABSOLUTAMENTE COMPROBADA "
        "MEDIANTE LA EPICRISIS Y LOS HALLAZGOS DESCRITOS EN LA HISTORIA "
        "CLÍNICA, POR LO QUE LA GLOSA ES TEMERARIA Y SE EXIGE SU PAGO "
        "TOTAL DE CONFORMIDAD CON LOS ACUERDOS CONTRACTUALES VIGENTES.",
        # 3) Ingreso a UCI supuestamente injustificado (APACHE / SOFA)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE INGRESO A UNIDAD DE "
        "CUIDADOS INTENSIVOS (UCI) SUPUESTAMENTE INJUSTIFICADO, YA QUE AL "
        "MOMENTO DE LA VALORACIÓN POR EL INTENSIVISTA, EL PACIENTE CUMPLÍA "
        "RIGUROSAMENTE CON LOS CRITERIOS CLÍNICOS DE INGRESO ESCALONADO "
        "BASADOS EN LOS PUNTAJES DE GRAVEDAD INTERNACIONALES (APACHE II / "
        "SOFA), DEBIDO A FALLA MULTIORGÁNICA, INSUFICIENCIA RESPIRATORIA "
        "AGUDA Y REQUERIMIENTO INMINENTE DE SOPORTE VASOPRESOR Y "
        "VENTILACIÓN MECÁNICA INVASIVA. NEGAR EL ACCESO A LA UCI HUBIERA "
        "RESULTADO FATAL. LA JUSTIFICACIÓN DEL INGRESO Y EL MANEJO POR "
        "CUIDADOS CRÍTICOS ESTÁ PLENAMENTE DOCUMENTADA EN LAS EVOLUCIONES "
        "MÉDICAS Y REGISTROS DE MONITOREO CONTINUO. CUALQUIER INTENTO DE "
        "GLOSAR ESTE NIVEL DE COMPLEJIDAD DEMUESTRA UN PROFUNDO "
        "DESCONOCIMIENTO DE LA FISIOPATOLOGÍA DEL PACIENTE CRÍTICO, "
        "OBLIGANDO A LA EPS AL RECONOCIMIENTO ÍNTEGRO DE LAS ESTANCIAS Y "
        "PROCEDIMIENTOS ASOCIADOS.",
    ),
    "ME": (
        # 1) Medicamento NO PBS prescrito por MIPRES
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE MEDICAMENTO NO INCLUIDO "
        "EN EL PLAN DE BENEFICIOS DE SALUD (NO PBS) O EXCLUIDO DE LA CAPITA, "
        "YA QUE ESTOS FÁRMACOS FUERON PRESCRITOS POR EL MÉDICO TRATANTE A "
        "TRAVÉS DEL APLICATIVO MIPRES, CUMPLIENDO CON LA RUTA NORMATIVA Y "
        "TECNOLÓGICA ESTABLECIDA POR EL MINISTERIO DE SALUD Y PROTECCIÓN "
        "SOCIAL PARA SU GESTIÓN Y RECOBRO. ES RESPONSABILIDAD EXCLUSIVA DE "
        "LA EPS GESTIONAR EL RECONOCIMIENTO ECONÓMICO ANTE LA ADRES Y NO "
        "TRASLADAR LA CARGA FINANCIERA A LA IPS PRESTADORA DEL SERVICIO "
        "QUE SUMINISTRÓ EL MEDICAMENTO DE BUENA FE Y BAJO INDICACIÓN "
        "CLÍNICA ESTRICTA PARA SALVAGUARDAR LA SALUD DEL AFILIADO. SE "
        "APORTA LA PRESCRIPCIÓN CON EL NÚMERO DE REPORTE MIPRES DEBIDAMENTE "
        "DILIGENCIADA Y AVALADA, DEMOSTRANDO EL CUMPLIMIENTO DEL TRÁMITE "
        "REGLAMENTARIO, LO CUAL HACE IMPROCEDENTE LA RETENCIÓN DEL PAGO A "
        "NUESTRO HOSPITAL.",
        # 2) Dosificación / cantidades / antibioticoterapia
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE DOSIFICACIÓN EXCESIVA, "
        "CANTIDADES MAYORES A LAS PROMEDIO O TIEMPOS PROLONGADOS DE "
        "ANTIBIOTICOTERAPIA, TODA VEZ QUE LA POSOLOGÍA FUE AJUSTADA "
        "MINUCIOSAMENTE AL PESO, SUPERFICIE CORPORAL, TASA DE FILTRACIÓN "
        "GLOMERULAR Y RESPUESTA TERAPÉUTICA DEL PACIENTE, ACORDE A LA "
        "LITERATURA MÉDICA INTERNACIONAL Y AL PROTOCOLO FARMACOLÓGICO "
        "INSTITUCIONAL. LOS CULTIVOS Y EL ANTIBIOGRAMA REVELARON LA "
        "PRESENCIA DE UN GERMEN MULTIRRESISTENTE QUE OBLIGÓ AL EQUIPO DE "
        "INFECTOLOGÍA A AMPLIAR Y MANTENER EL ESQUEMA TERAPÉUTICO "
        "INTRAVENOSO EN DOSIS MÁXIMAS PARA ERRADICAR LA SEPSIS. CUESTIONAR "
        "LAS CANTIDADES ADMINISTRADAS CUANDO ESTAS FUERON VITALES PARA LA "
        "SUPERVIVENCIA DEL PACIENTE ES TÉCNICAMENTE ABSURDO. LA HOJA DE "
        "ADMINISTRACIÓN DE MEDICAMENTOS CONFIRMA EL CONSUMO REAL, "
        "EXIGIENDO SU PAGO TOTAL.",
        # 3) CUM comercial vs genérico (desabastecimiento INVIMA)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE DISCORDANCIA ENTRE EL "
        "CÓDIGO CUM FACTURADO Y EL ACUERDO PACTADO (USO DE MEDICAMENTO "
        "COMERCIAL EN LUGAR DE GENÉRICO), PUES AL MOMENTO DE LA ATENCIÓN "
        "HOSPITALARIA EXISTÍA UN DESABASTECIMIENTO NACIONAL COMPROBADO DEL "
        "PRINCIPIO ACTIVO EN SU PRESENTACIÓN GENÉRICA, HECHO DEMOSTRABLE "
        "MEDIANTE LA ALERTA SANITARIA EMITIDA POR EL INVIMA. ANTE ESTA "
        "SITUACIÓN DE FUERZA MAYOR, NUESTRA INSTITUCIÓN PRIORIZÓ EL "
        "DERECHO FUNDAMENTAL A LA VIDA Y PROCEDIÓ A ADMINISTRAR LA "
        "ALTERNATIVA COMERCIAL DISPONIBLE EN EL STOCK DE FARMACIA PARA NO "
        "INTERRUMPIR EL TRATAMIENTO CRÍTICO. ESTA DECISIÓN ESTÁ AMPARADA "
        "POR EL PRINCIPIO DEL BENEFICIO AL ENFERMO Y LA NECESIDAD MÉDICA. "
        "LA FACTURACIÓN CORRESPONDE EXACTAMENTE AL FÁRMACO ADMINISTRADO, "
        "SIENDO TOTALMENTE JUSTIFICADO EL COBRO Y OBLIGATORIO SU "
        "RECONOCIMIENTO POR PARTE DE LA EPS.",
    ),
    "IN": (
        # 1) Insumos incluidos en derechos de sala
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE INSUMOS SUPUESTAMENTE "
        "INCLUIDOS EN LOS DERECHOS DE SALA DE CIRUGÍA O ESTANCIA "
        "HOSPITALARIA, YA QUE LOS ELEMENTOS ITEMIZADOS Y FACTURADOS "
        "(TALES COMO SUTURAS MECÁNICAS, HEMOSTÁTICOS ESPECIALES DE ALTA "
        "TECNOLOGÍA O SELLANTES TISULARES) SUPERAN AMPLIAMENTE LOS TOPES, "
        "CARACTERÍSTICAS Y CANTIDADES DEL MATERIAL BÁSICO DESCRITO EN LOS "
        "CAPÍTULOS CORRESPONDIENTES DEL MANUAL TARIFARIO PACTADO. LA "
        "COMPLEJIDAD DE LA INTERVENCIÓN QUIRÚRGICA DEMANDÓ LA UTILIZACIÓN "
        "DE DISPOSITIVOS ESPECIALIZADOS PARA MINIMIZAR EL TIEMPO "
        "OPERATORIO Y PREVENIR HEMORRAGIAS MASIVAS, BENEFICIANDO "
        "DIRECTAMENTE LA RECUPERACIÓN DEL PACIENTE. ESTOS INSUMOS NO "
        "PUEDEN SER ASUMIDOS COMO PÉRDIDA POR EL HOSPITAL, YA QUE SU USO "
        "ESTÁ DEBIDAMENTE PLASMADO EN LA DESCRIPCIÓN QUIRÚRGICA, "
        "OBLIGANDO A LA EPS A SU PAGO MEDIANTE FACTURACIÓN ADICIONAL POR "
        "EVENTO.",
        # 2) Material osteosíntesis no autorizado (decisión intraoperatoria)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE MATERIAL DE OSTEOSÍNTESIS "
        "NO AUTORIZADO PREVIAMENTE O POR CANTIDADES DIFERENTES A LAS "
        "PRESCRITAS INICIALMENTE, PUES ESTE MATERIAL FUE UTILIZADO EN EL "
        "MARCO DE UNA CIRUGÍA DE URGENCIA POR TRAUMA SEVERO. EN ESTOS "
        "ESCENARIOS, EL ORTOPEDISTA TRATANTE DECIDE EL TIPO, MEDIDA Y "
        "CANTIDAD DEL DISPOSITIVO IDÓNEO DE FORMA INTRAOPERATORIA, SEGÚN "
        "LOS HALLAZGOS ANATÓMICOS REALES Y EL TIPO DE FRACTURA EVIDENCIADA "
        "BAJO VISIÓN DIRECTA, CONDICIONES IMPOSIBLES DE PREDECIR CON "
        "EXACTITUD EN UNA EVALUACIÓN PREQUIRÚRGICA. CONDICIONAR EL PAGO DE "
        "ESTOS IMPLANTES A UNA AUTORIZACIÓN EXACTA PREVIA CONSTITUYE UN "
        "ABSURDO CLÍNICO. LA TRAZABILIDAD DEL MATERIAL QUEDÓ REGISTRADA "
        "CON SUS RESPECTIVOS STICKERS DEL INVIMA EN LA HISTORIA CLÍNICA, "
        "POR LO CUAL SU PAGO DEBE SER RECONOCIDO EN SU TOTALIDAD Y SIN "
        "DEMORAS.",
        # 3) Dispositivos no reutilizables (bioseguridad / IAAS)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE COBRO INDIVIDUALIZADO DE "
        "DISPOSITIVOS MÉDICOS O INSUMOS NO REUTILIZABLES, BAJO EL "
        "ARGUMENTO DE QUE DEBIERON SER DESINFECTADOS PARA PRÓXIMOS "
        "PACIENTES, YA QUE LA RESOLUCIÓN INSTITUCIONAL DEL COMITÉ DE "
        "INFECCIONES DEL HUS Y LAS DIRECTRICES TÉCNICAS DEL INVIMA "
        "PROHÍBEN ESTRICTAMENTE EL REÚSO DE ESTE TIPO ESPECÍFICO DE "
        "CATÉTERES O ELEMENTOS INVASIVOS DEBIDO AL ALTO RIESGO DE "
        "INFECCIONES ASOCIADAS A LA ATENCIÓN EN SALUD (IAAS). SALVAGUARDAR "
        "LA BIOSEGURIDAD DEL PACIENTE ES UNA OBLIGACIÓN INELUDIBLE Y DE "
        "ORDEN LEGAL. EN CONSECUENCIA, EL HOSPITAL DEBE ABRIR UN "
        "DISPOSITIVO NUEVO Y ESTÉRIL PARA CADA ATENCIÓN, LO QUE JUSTIFICA "
        "PLENAMENTE EL COBRO ÍNTEGRO DEL ELEMENTO. RECHAZAMOS VEHEMENTEMENTE "
        "ESTA GLOSA TEMERARIA QUE PRETENDE INDUCIR A PRÁCTICAS INSEGURAS "
        "PARA AHORRAR COSTOS.",
    ),
    "CO": (
        # 1) Paciente retirado / desafiliado al momento de la atención (BDUA)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE PACIENTE RETIRADO, "
        "DESAFILIADO O PERTENECIENTE A OTRA EPS AL MOMENTO DE LA ATENCIÓN, "
        "YA QUE AL REALIZAR LA VERIFICACIÓN DE DERECHOS A LA HORA EXACTA "
        "DEL INGRESO DEL USUARIO A NUESTRA INSTITUCIÓN, EL SISTEMA "
        "TRANSACCIONAL DE CONSULTA EN LA BASE DE DATOS ÚNICA DE AFILIADOS "
        "(BDUA) Y EL PORTAL ADRES ARROJABAN QUE EL PACIENTE SE ENCONTRABA "
        'EN ESTADO "ACTIVO" CON SU ENTIDAD. LA CORTE CONSTITUCIONAL Y LA '
        "SUPERINTENDENCIA DE SALUD HAN SIDO CLARAS EN QUE LAS IPS NO "
        "PUEDEN ASUMIR LAS DEFICIENCIAS, LENTITUD O DESACTUALIZACIÓN EN "
        "LOS SISTEMAS DE INFORMACIÓN Y REPORTE DE NOVEDADES DE LAS EPS. "
        "EL HOSPITAL UNIVERSITARIO DE SANTANDER ACTUÓ DE BUENA FE Y "
        "PRESTÓ EL SERVICIO CONFIANDO EN LA VERACIDAD DE LAS PLATAFORMAS "
        "OFICIALES DEL ESTADO, POR LO CUAL LA EPS ESTÁ EN LA OBLIGACIÓN "
        "CONTRACTUAL Y LEGAL DE PAGAR LA TOTALIDAD DE LA CUENTA.",
        # 2) Servicio incluido en PGP / capitada (urgencia o exclusión expresa)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE SERVICIO SUPUESTAMENTE "
        "INCLUIDO DENTRO DEL PAGO GLOBAL PROSPECTIVO (PGP) O DE LA "
        "MODALIDAD CAPITADA, YA QUE LA ATENCIÓN CORRESPONDE A UNA "
        "URGENCIA DE ALTA COMPLEJIDAD O A UNA PATOLOGÍA QUE HACE PARTE "
        "EXPRESA DE LAS EXCLUSIONES ESPECÍFICAS DECLARADAS EN EL ANEXO "
        "TÉCNICO FIRMADO ENTRE LAS PARTES. EL CONTRATO ES CLARO AL "
        "DETERMINAR QUE CIERTOS EVENTOS CATASTRÓFICOS, TRAUMAS MAYORES O "
        "MANEJOS EN UCI REBASAN LA FRECUENCIA Y EL RIESGO ASUMIDO EN LA "
        "NOTA TÉCNICA CAPITADA, POR LO CUAL DEBEN SER FACTURADOS Y "
        "RECONOCIDOS MEDIANTE LA MODALIDAD DE PAGO POR EVENTO A LAS "
        "TARIFAS ESTIPULADAS. LA INTENCIÓN DE LA EPS DE ENGLOBAR SERVICIOS "
        "EXCLUIDOS DENTRO DE UNA TARIFA FIJA VIOLA EL EQUILIBRIO ECONÓMICO "
        "DEL CONTRATO, HACIENDO NECESARIO EL LEVANTAMIENTO INMEDIATO Y EL "
        "PAGO FRONTERIZO DEL VALOR FACTURADO.",
        # 3) Servicios fuera del área geográfica (portabilidad nacional)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE SERVICIOS PRESTADOS A "
        "PACIENTES FUERA DEL ÁREA DE COBERTURA GEOGRÁFICA DE LA EPS, PUES "
        "AL TRATARSE DE UN HOSPITAL UNIVERSITARIO DE TERCER Y CUARTO "
        "NIVEL DE ATENCIÓN (NIVEL DE EXCELENCIA), RECIBIMOS REFERENCIAS "
        "DEPARTAMENTALES Y NACIONALES ANTE LA INCAPACIDAD RESOLUTIVA DE "
        "LAS REDES BÁSICAS. ESTO SE ENCUENTRA ABSOLUTAMENTE AMPARADO POR "
        "EL PRINCIPIO DE PORTABILIDAD NACIONAL ESTABLECIDO EN LA "
        "LEGISLACIÓN COLOMBIANA, EL CUAL GARANTIZA QUE UN CIUDADANO PUEDA "
        "RECIBIR ATENCIÓN EN CUALQUIER PARTE DEL TERRITORIO SIN QUE "
        "CUESTIONES GEOGRÁFICAS LIMITEN SU DERECHO FUNDAMENTAL A LA SALUD "
        "Y A LA VIDA. LA CONDICIÓN CRÍTICA DEL AFILIADO REQUERÍA LA "
        "TECNOLOGÍA Y EL TALENTO HUMANO ESPECIALIZADO QUE SOLO EL HUS "
        "PODÍA BRINDAR. SE EXIGE A LA EPS RECONOCER Y PROCEDER CON EL "
        "PAGO ÍNTEGRO DEL EVENTO.",
    ),
    "FA": (
        # 1) Devolución total por errores aritméticos / digitación
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE DEVOLUCIÓN TOTAL DE LA "
        "FACTURA AMPARADA EN SUPUESTOS ERRORES ARITMÉTICOS O DE DIGITACIÓN "
        "MENORES, YA QUE LA RESOLUCIÓN 2335 DE 2023, EN CONCORDANCIA CON EL "
        "MANUAL ÚNICO DE GLOSAS Y DEVOLUCIONES DEL MINISTERIO DE SALUD, "
        "ESTABLECE DE FORMA TAJANTE QUE LOS ERRORES MATEMÁTICOS O "
        "INCONSISTENCIAS EN UN ÍTEM ESPECÍFICO SE DEBEN SUBSANAR MEDIANTE "
        "LA APLICACIÓN DE UNA GLOSA PARCIAL (CON LA CONSECUENTE GENERACIÓN "
        "DE NOTAS CRÉDITO O DÉBITO) Y NO CONSTITUYEN BAJO NINGUNA "
        "CIRCUNSTANCIA CAUSAL LEGAL PARA LA DEVOLUCIÓN ABUSIVA DE TODA LA "
        "CUENTA MÉDICA. DEVOLVER LA FACTURA COMPLETA ES UNA ESTRATEGIA "
        "DILATORIA PARA EVADIR LOS TIEMPOS DE GIRO Y AFECTAR EL FLUJO DE "
        "CAJA DE LA INSTITUCIÓN PRESTADORA, POR LO QUE ESTA ACTUACIÓN SERÁ "
        "REPORTADA A LA SUPERINTENDENCIA NACIONAL DE SALUD SI NO SE "
        "PROCEDE CON LA ACEPTACIÓN DE LA FACTURA Y EL PAGO INMEDIATO DE "
        "LO NO GLOSADO.",
        # 2) RIPS inconsistentes (CUV de recepción exitosa)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE REGISTROS INDIVIDUALES DE "
        "PRESTACIÓN DE SERVICIOS (RIPS) INCONSISTENTES O SUPUESTAMENTE NO "
        "RECIBIDOS, PUES TODOS LOS ARCHIVOS PLANOS FUERON VALIDADOS "
        "PREVIAMENTE EN LA PLATAFORMA DISPUESTA PARA TAL FIN Y, AL "
        "MOMENTO DE LA RADICACIÓN ELECTRÓNICA DE LA FACTURA, SE GENERÓ EL "
        "CÓDIGO ÚNICO DE VALIDACIÓN (CUV) DE RECEPCIÓN EXITOSA SIN "
        "ERRORES DE ESTRUCTURA NI RECHAZOS. ESTE ACUSE DE RECIBO DIGITAL "
        "ES LA PRUEBA IRREFUTABLE DE QUE EL HOSPITAL UNIVERSITARIO DE "
        "SANTANDER CUMPLIÓ CON LA ESTRUCTURA TÉCNICA DEL ANEXO DE "
        "FACTURACIÓN ELECTRÓNICA EN SALUD (RESOLUCIÓN 510 DE 2022 Y 2284 "
        "DE 2023). SI LA EPS PRESENTA FALLAS EN SUS SISTEMAS DE LECTURA E "
        "IMPORTACIÓN DE DATOS, ESTE PROBLEMA TECNOLÓGICO INTERNO NO PUEDE "
        "TRADUCIRSE EN UNA GLOSA INJUSTA PARA EL PRESTADOR. EXIGIMOS LA "
        "CANCELACIÓN DEL TÍTULO VALOR CON SUS RESPECTIVOS INTERESES "
        "MORATORIOS.",
        # 3) Extemporaneidad (fuerza mayor por caída de plataforma EPS)
        "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE EXTEMPORANEIDAD EN LA "
        "PRESENTACIÓN Y RADICACIÓN DE LA FACTURA, YA QUE SE ENCUENTRA "
        "PLENAMENTE DEMOSTRADO MEDIANTE OFICIOS, CORREOS ELECTRÓNICOS Y "
        "CAPTURAS DE PANTALLA CERTIFICADAS, QUE LA DEMORA OBEDECIÓ A "
        "CAÍDAS RECURRENTES, MANTENIMIENTOS NO PROGRAMADOS Y BLOQUEOS "
        "TÉCNICOS DE LA PLATAFORMA DE RECEPCIÓN DE RADICACIÓN DE LA "
        "PROPIA EPS. ESTA INTERRUPCIÓN DE LA DISPONIBILIDAD TECNOLÓGICA "
        "CONSTITUYE UNA SITUACIÓN DE FUERZA MAYOR ATRIBUIBLE EXCLUSIVAMENTE "
        "A LA ENTIDAD ASEGURADORA, LO CUAL INTERRUMPE LOS TÉRMINOS LEGALES "
        "DE PRESENTACIÓN SEGÚN EL DECRETO REGLAMENTARIO VIGENTE. EL "
        "HOSPITAL NO PERDERÁ EL DERECHO AL COBRO DE SERVICIOS EFECTIVAMENTE "
        "PRESTADOS POR INEFICIENCIAS TECNOLÓGICAS DE TERCEROS. SE SOLICITA "
        "EL DESISTIMIENTO DE ESTA GLOSA ADMINISTRATIVA Y LA AUTORIZACIÓN "
        "INMEDIATA PARA EL PAGO DE LOS SERVICIOS ASISTENCIALES CUMPLIDOS.",
    ),
}

# Familias compatibles con códigos PE (pertinencia) ↔ CL y DE (devolución)
# ↔ FA — se reutilizan los mismos few-shots para no duplicar contenido.
_ALIAS_FAMILIA = {
    "PE": "CL",  # Pertinencia clínica usa los CL
    "DE": "FA",  # Devolución usa los FA
}


def familia_de_codigo(codigo: str) -> str:
    """Devuelve la familia normalizada (2 letras MAYUS) para un código.

    'AU0301' → 'AU'. 'DE0101' → 'FA' (alias). 'PE0801' → 'CL' (alias).
    Si el código está vacío o no tiene formato esperado, devuelve ''.
    """
    if not codigo or len(codigo) < 2:
        return ""
    prefijo = codigo[:2].upper()
    return _ALIAS_FAMILIA.get(prefijo, prefijo)


def bloque_banco_respuestas(codigo: str, max_ejemplos: int = 2) -> str:
    """Bloque de few-shots para el user prompt según la familia del código.

    Inyecta `max_ejemplos` respuestas modelo del HUS para que la IA imite
    el **estilo, estructura y tono** sin copiarlas literalmente. Aclara
    que son punto de partida — la IA debe adaptarlas con los datos reales
    del caso (paciente, valor, fechas, contrato, datos clínicos).

    Devuelve cadena vacía si la familia no está en el banco — el flujo
    sigue normal sin el bloque.
    """
    familia = familia_de_codigo(codigo)
    ejemplos = BANCO_HUS.get(familia)
    if not ejemplos:
        return ""
    n = min(max(1, max_ejemplos), len(ejemplos))
    seleccion = ejemplos[:n]
    nombre_familia = {
        "AU": "AUTORIZACIONES",
        "TA": "TARIFAS",
        "SO": "SOPORTES",
        "CL": "CLÍNICO / PERTINENCIA",
        "ME": "MEDICAMENTOS",
        "IN": "INSUMOS Y DISPOSITIVOS MÉDICOS",
        "CO": "COBERTURA Y CONTRATACIÓN",
        "FA": "FACTURACIÓN",
    }.get(familia, familia)

    out = (
        "\n═══════════════ BANCO DE RESPUESTAS DEL HUS — ESTILO INSTITUCIONAL "
        "═══════════════\n"
        f"[CÓDIGO {familia} — {nombre_familia}]\n"
        f"A continuación encontrarás {n} respuestas tipo del banco oficial del "
        "ESE HUS para esta familia. ÚSALAS COMO PATRÓN DE ESTILO, ESTRUCTURA "
        "Y TONO — NO LAS COPIES LITERALMENTE. Son respuestas GENÉRICAS que "
        "sirven de PUNTO DE PARTIDA: tu dictamen debe ser una versión más "
        "TÉCNICA y PULIDA que integre los datos reales del caso concreto "
        "(EPS, contrato, valor, fechas, datos clínicos, CUPS, etc.).\n\n"
        "OBSERVA Y REPLICA:\n"
        "  • Apertura: 'ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE…'\n"
        "  • Citas normativas con número EXACTO (Ley NNN de YYYY, "
        "Resolución NNNN de YYYY, Decreto NNN de YYYY, Art. N)\n"
        "  • Tono firme y resolutivo, sin condicionales débiles\n"
        "  • Cierre exigiendo el levantamiento total + pago inmediato\n"
        "  • Terminología jurídico-médica precisa\n\n"
        "RESPUESTAS DE REFERENCIA:\n"
    )
    for i, ej in enumerate(seleccion, 1):
        out += f"\n— EJEMPLO {i} —\n{ej}\n"
    out += (
        "\nAHORA REDACTA tu propio dictamen siguiendo este patrón pero "
        f"adaptado al caso concreto (EPS específica, contrato vigente, valor "
        f"facturado, datos clínicos, código {codigo}). No menciones que "
        "existe un 'banco de respuestas'.\n"
        "═══════════════════════════════════════════════════════════════════"
        "════════════════\n"
    )
    return out
