"""estado_inicial_esquema

Revision ID: ca03329c3e5b
Revises: 
Create Date: 2026-05-20 15:21:20.110207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca03329c3e5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nota_workflow')
    op.drop_column('usuarios', 'workload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('workload', sa.INTEGER(), server_default=sa.text('(100)'), nullable=True))
    op.add_column('usuarios', sa.Column('nota_workflow', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
