# -*- coding: utf-8 -*-
"""
BANCO DE OBJECIONES DE GLOSAS — ESE HOSPITAL UNIVERSITARIO DE SANTANDER
========================================================================
Diccionario maestro de plantillas de respuesta a glosas médicas para
auditoría de cuentas contra todas las ERP (EPS, ARL, IPS, EPSS) sin
necesidad de un contrato bilateral firmado.

Estructura:
- CONCEPTOS_GENERALES: 50 conceptos (10 por grupo) aplicables a CUALQUIER pagador
- ENTIDADES_CON_CONTRATO: dict con plantillas específicas firmadas (9 entidades)

Uso típico:
    from banco_objeciones_glosas_hus import CONCEPTOS_GENERALES, render
    texto = render(CONCEPTOS_GENERALES['TA']['TA-G01'], pagador="MUTUALSER EPS")
    print(texto)

Autor: AUD SINAC SC — SINAC SC SAS (NIT 901.475.283-4)
Cliente: ESE Hospital Universitario de Santander (NIT 900.006.037-4)
Versión: 1.0 — Mayo 2026
"""

# =============================================================================
# ENCABEZADO Y CIERRE ESTÁNDAR
# =============================================================================

ENCABEZADO_STD = "ESE HUS NO ACEPTA GLOSA POR CONCEPTO DE "
CIERRE_STD = " SE SOLICITA EL LEVANTAMIENTO DE LA GLOSA Y EL PAGO ÍNTEGRO DE LO FACTURADO."

# =============================================================================
# CONCEPTOS GENERALES — 50 PLANTILLAS (10 POR GRUPO) APLICABLES SIN CONTRATO
# =============================================================================

CONCEPTOS_GENERALES = {
    # -------------------------------------------------------------------------
    # GRUPO 1 — TARIFAS (TA) — 10 conceptos
    # -------------------------------------------------------------------------
    "TA": {
        "TA-G01": {
            "titulo": "MAYOR VALOR COBRADO — TARIFA INSTITUCIONAL HUS POR RESOLUCIÓN",
            "texto": (
                ENCABEZADO_STD + "PRESUNTO MAYOR VALOR COBRADO (MVC) SOBRE ÍTEM LIQUIDADO "
                "CON TARIFA PROPIA INSTITUCIONAL, DADO QUE EL VALOR FACTURADO CORRESPONDE "
                "EXACTAMENTE A LA TARIFA APROBADA MEDIANTE ACTO ADMINISTRATIVO INSTITUCIONAL "
                "DE LA ESE HOSPITAL UNIVERSITARIO DE SANTANDER (RESOLUCIÓN HUS VIGENTE A LA "
                "FECHA DE PRESTACIÓN). EN AUSENCIA DE CONTRATO BILATERAL FORMAL ENTRE EL HUS "
                "Y {PAGADOR}, EL VALOR FACTURADO TIENE FUNDAMENTO LEGAL DIRECTO EN EL "
                'ARTÍCULO 87 DEL DECRETO 2423 DE 1996 QUE ESTABLECE: "POR LAS '
                "CIRCUNSTANCIAS DE ORDEN TECNOLÓGICO, CUANDO ALGUNA INSTITUCIÓN PRESTADORA "
                "DE SERVICIOS DE SALUD REALICE UN PROCEDIMIENTO QUE NO SE ENCUENTRE "
                "DEFINIDO Y POR LO TANTO NO TENGA ASIGNADA TARIFA, ÉSTE SE RECONOCERÁ POR "
                'LA TARIFA QUE TENGA DEFINIDA LA INSTITUCIÓN". LO ANTERIOR ARMONIZA CON EL '
                "ARTÍCULO 1602 DEL CÓDIGO CIVIL Y CON EL ARTÍCULO 2.5.3.8.4.2.7 DEL DECRETO "
                "780 DE 2016." + CIERRE_STD
            ),
        },
        "TA-G02": {
            "titulo": "APLICACIÓN ESQUEMA SOAT VIGENTE — DECRETO 2423/1996",
            "texto": (
                ENCABEZADO_STD + "DIFERENCIA TARIFARIA EN ÍTEM LIQUIDADO BAJO ESQUEMA SOAT "
                "VIGENTE, DADO QUE EL CÁLCULO APLICADO CORRESPONDE EXACTAMENTE AL VALOR "
                "ESTABLECIDO EN EL MANUAL TARIFARIO SOAT (DECRETO 2423 DE 1996 Y SUS "
                "MODIFICACIONES POSTERIORES) PARA EL CÓDIGO HOMOLOGADO DEL CUPS FACTURADO, "
                "EXPRESADO EN SALARIO MÍNIMO DIARIO LEGAL VIGENTE (SMDLV) PARA LA VIGENCIA "
                "DE PRESTACIÓN DEL SERVICIO. LA HOMOLOGACIÓN ENTRE CUPS Y CÓDIGO SOAT FUE "
                "REALIZADA CONFORME A LAS TABLAS DE EQUIVALENCIAS OFICIALES DEL MINISTERIO "
                "DE SALUD Y EL VALOR LIQUIDADO COINCIDE CON LA TARIFA SOAT PLENO. {PAGADOR} "
                "NO HA APORTADO ELEMENTOS DE PRUEBA QUE DEMUESTREN LA EXISTENCIA DE UNA "
                "TARIFA PACTADA DISTINTA O INFERIOR." + CIERRE_STD
            ),
        },
        "TA-G03": {
            "titulo": "RESOLUCIÓN HUS 194/2025 — MATERIAL DE OSTEOSÍNTESIS (MAOS)",
            "texto": (
                ENCABEZADO_STD + "DIFERENCIA EN VALOR DE MATERIAL DE OSTEOSÍNTESIS, ÓRTESIS "
                "O PRÓTESIS, DADO QUE EL VALOR FACTURADO CORRESPONDE EXACTAMENTE AL "
                'ESTABLECIDO EN LA RESOLUCIÓN HUS No. 194 DEL 15 DE MAYO DE 2025 "POR '
                "MEDIO DE LA CUAL SE CREAN CÓDIGOS Y TARIFAS INSTITUCIONALES PARA MATERIAL "
                "DE OSTEOSÍNTESIS, EN LA EMPRESA SOCIAL DEL ESTADO HOSPITAL UNIVERSITARIO "
                'DE SANTANDER" (ANEXO No. 9), LA CUAL DEROGÓ EL ARTÍCULO NOVENO DE LA '
                "RESOLUCIÓN HUS No. 171 DEL 30 DE ABRIL DE 2024. LA RESOLUCIÓN HUS 194/2025 "
                "ESTÁ AMPARADA POR EL ARTÍCULO 87 DEL DECRETO 2423 DE 1996 Y EL ARTÍCULO "
                "2.5.3.8.4.2.7 NUMERAL 5 DEL DECRETO 780 DE 2016, Y ES OPONIBLE A {PAGADOR} "
                "EN AUSENCIA DE TARIFA PACTADA DIVERGENTE." + CIERRE_STD
            ),
        },
        "TA-G04": {
            "titulo": "MEDICAMENTOS Y DISPOSITIVOS REGULADOS — CNPMD + SISMED",
            "texto": (
                ENCABEZADO_STD + "DIFERENCIA EN VALOR DE MEDICAMENTOS, DISPOSITIVOS MÉDICOS "
                "O INSUMOS REGULADOS, DADO QUE LOS VALORES FACTURADOS CORRESPONDEN A LOS "
                "PRECIOS REGULADOS POR LA COMISIÓN NACIONAL DE PRECIOS DE MEDICAMENTOS Y "
                "DISPOSITIVOS MÉDICOS (CNPMD) — CIRCULAR 03 DE 2013 Y SUS MODIFICACIONES — "
                "Y POR EL SISTEMA DE INFORMACIÓN DE PRECIOS DE MEDICAMENTOS (SISMED). PARA "
                "MEDICAMENTOS INSTITUCIONALES, EL HUS APLICA LA TARIFA ESTABLECIDA EN "
                "RESOLUCIÓN INSTITUCIONAL VIGENTE, AMPARADA POR EL ARTÍCULO 87 DEL DECRETO "
                "2423 DE 1996. PARA INSUMOS, SE APLICAN LOS CÓDIGOS PROPIOS HUS CON SU "
                "RESPECTIVA TARIFA INSTITUCIONAL." + CIERRE_STD
            ),
        },
        "TA-G05": {
            "titulo": "PRELACIÓN DE TARIFA INSTITUCIONAL SOBRE ESQUEMA SOAT",
            "texto": (
                ENCABEZADO_STD + "PRETENSIÓN DE APLICAR ESQUEMA SOAT A ÍTEM QUE CUENTA CON "
                "TARIFA INSTITUCIONAL HUS, DADO QUE EL ESQUEMA TARIFARIO INSTITUCIONAL DEL "
                "HUS PREVALECE SOBRE EL MANUAL SOAT PARA PROCEDIMIENTOS DE ALTA "
                "COMPLEJIDAD, NEUROCIRUGÍA, CIRUGÍA DE CABEZA Y CUELLO, ONCOLOGÍA, "
                "TRASPLANTES, CARDIOVASCULAR Y OTRAS ESPECIALIDADES DONDE EL HUS POSEE "
                "ACTO ADMINISTRATIVO PROPIO. EL ARTÍCULO 87 DEL DECRETO 2423 DE 1996 "
                "ESTABLECE LA PRELACIÓN DE LA TARIFA INSTITUCIONAL CUANDO ESTA EXISTE: "
                '"SE RECONOCERÁ POR LA TARIFA QUE TENGA DEFINIDA LA INSTITUCIÓN". '
                "INTERPRETAR EN SENTIDO OPUESTO VULNERA EL ARTÍCULO 1622 DEL CÓDIGO CIVIL "
                "(INTERPRETACIÓN INTEGRAL) Y EL 1620 (EFECTO ÚTIL)." + CIERRE_STD
            ),
        },
        "TA-G06": {
            "titulo": "VIGENCIA TARIFARIA — FECHA DE PRESTACIÓN PRECEDE AJUSTE",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA APLICACIÓN DE TARIFA INDEBIDA O DESACTUALIZADA, "
                "DADO QUE LA TARIFA APLICADA AL ÍTEM FACTURADO CORRESPONDE EXACTAMENTE A "
                "LA VIGENTE EN LA RESOLUCIÓN HUS Y/O EN EL MANUAL SOAT PARA LA FECHA "
                "EFECTIVA DE PRESTACIÓN DEL SERVICIO, DE CONFORMIDAD CON EL PRINCIPIO DE "
                "LEGALIDAD TARIFARIA. CUALQUIER MODIFICACIÓN POSTERIOR DEL TARIFARIO NO "
                "PUEDE APLICARSE RETROACTIVAMENTE A SERVICIOS YA PRESTADOS, EN APLICACIÓN "
                "DEL PRINCIPIO DE IRRETROACTIVIDAD DE LAS NORMAS Y DEL ARTÍCULO 17 DEL "
                "CÓDIGO CIVIL. LA AUDITORÍA DE {PAGADOR} NO ESTÁ FACULTADA PARA MODIFICAR "
                "LAS TARIFAS POR VÍA DE GLOSA." + CIERRE_STD
            ),
        },
        "TA-G07": {
            "titulo": "PAQUETES QUIRÚRGICOS — INCLUSIONES Y EXCLUSIONES",
            "texto": (
                ENCABEZADO_STD + "DIFERENCIA EN VALOR DE PAQUETE QUIRÚRGICO O "
                "DESCONOCIMIENTO DE LA INCLUSIÓN DE CUPS DENTRO DEL PAQUETE, DADO QUE EL "
                "VALOR FACTURADO CORRESPONDE EXACTAMENTE AL PAQUETE INSTITUCIONAL HUS CON "
                "SU DESAGREGACIÓN DE CUPS INCLUIDOS Y EXCLUIDOS PUBLICADA EN EL ANEXO "
                "TARIFARIO VIGENTE A LA FECHA DE PRESTACIÓN. EL PAQUETE INCLUYE LOS "
                "SERVICIOS, INSUMOS Y MEDICAMENTOS ESPECÍFICAMENTE LISTADOS, Y EXCLUYE "
                "AQUELLOS NO ENUNCIADOS EXPRESAMENTE COMO INCLUSIÓN, LOS CUALES SE "
                "FACTURAN POR SEPARADO. {PAGADOR} NO HA APORTADO PRUEBA DOCUMENTAL DE UNA "
                "DESAGREGACIÓN DISTINTA NI HA SUSCRITO ACUERDO QUE MODIFIQUE LAS "
                "INCLUSIONES ESTÁNDAR DEL PAQUETE." + CIERRE_STD
            ),
        },
        "TA-G08": {
            "titulo": "ACUERDO TÁCITO POR CONTINUIDAD EN LA PRESTACIÓN — ART. 824 C.CO.",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE PACTO TARIFARIO ENTRE LAS PARTES, "
                "DADO QUE LA RELACIÓN HUS-{PAGADOR} SE HA EJECUTADO BAJO UN ACUERDO TÁCITO "
                "DE VOLUNTADES PERFECCIONADO POR LA CONTINUIDAD EN LA REMISIÓN DE USUARIOS "
                "POR PARTE DE {PAGADOR}, LA ACEPTACIÓN DE LA PRESTACIÓN DE SERVICIOS POR "
                "PARTE DEL HUS Y EL PAGO HISTÓRICO DE FACTURAS BAJO EL ESQUEMA TARIFARIO "
                "DEL HUS, CONFIGURANDO UN ACUERDO TÁCITO EN LOS TÉRMINOS DE LOS ARTÍCULOS "
                "824 Y 871 DEL CÓDIGO DE COMERCIO Y DEL ARTÍCULO 1603 DEL CÓDIGO CIVIL "
                "(BUENA FE). LA AUSENCIA DE CONTRATO ESCRITO NO PUEDE INVOCARSE COMO "
                "EXCUSA PARA EL NO PAGO DE SERVICIOS EFECTIVAMENTE PRESTADOS, CONFORME A "
                "JURISPRUDENCIA REITERADA DE LA CORTE SUPREMA DE JUSTICIA Y A LA "
                "SUPERINTENDENCIA NACIONAL DE SALUD." + CIERRE_STD
            ),
        },
        "TA-G09": {
            "titulo": "ESTANCIA HOSPITALARIA Y SERVICIOS COMPLEMENTARIOS — DESAGREGACIÓN",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA DOBLE FACTURACIÓN ENTRE ESTANCIA HOSPITALARIA Y "
                "SERVICIOS COMPLEMENTARIOS, DADO QUE LA TARIFA DE ESTANCIA HOSPITALARIA "
                "(GENERAL, MEDIA O ESPECIAL) CUBRE ÚNICAMENTE LOS RUBROS EXPRESAMENTE "
                "DEFINIDOS EN LA RESOLUCIÓN INSTITUCIONAL HUS Y EN EL DECRETO 2423 DE 1996, "
                "EXCLUYENDO MEDICAMENTOS, INSUMOS, AYUDAS DIAGNÓSTICAS, INTERCONSULTAS, "
                "PROCEDIMIENTOS, MATERIAL DE OSTEOSÍNTESIS Y SERVICIOS PROFESIONALES, LOS "
                "CUALES SE FACTURAN POR SEPARADO. LA HOMOLOGACIÓN DE LA ESTANCIA NO IMPIDE "
                "EL COBRO DE LOS SERVICIOS ESPECÍFICOS EFECTIVAMENTE PRESTADOS DURANTE LA "
                "HOSPITALIZACIÓN, CONFORME A LA ESTRUCTURA TARIFARIA DEL MANUAL SOAT Y A "
                "LAS RESOLUCIONES INSTITUCIONALES." + CIERRE_STD
            ),
        },
        "TA-G10": {
            "titulo": "DERECHOS DE SALA, HONORARIOS Y CIRCULANTES — INCLUSIÓN EN TARIFA",
            "texto": (
                ENCABEZADO_STD + "PRESUNTO COBRO INDEBIDO DE DERECHOS DE SALA, HONORARIOS "
                "MÉDICOS O MATERIALES DE CIRCULANTE QUIRÚRGICO, DADO QUE ESTOS RUBROS SE "
                "FACTURAN CONFORME A LA ESTRUCTURA DEL MANUAL TARIFARIO SOAT (ARTÍCULOS "
                "11, 12 Y CONCORDANTES DEL DECRETO 2423 DE 1996) Y A LAS RESOLUCIONES "
                "INSTITUCIONALES DEL HUS QUE REGULAN LA DESAGREGACIÓN DE CADA PROCEDIMIENTO "
                "QUIRÚRGICO. LA DESAGREGACIÓN ENTRE HONORARIOS, DERECHOS DE SALA, "
                "MATERIALES Y MEDICAMENTOS ES OBLIGATORIA POR NORMATIVA Y NO CONSTITUYE "
                "DOBLE FACTURACIÓN. EL CIRCULANTE QUIRÚRGICO CORRESPONDE AL VALOR PROMEDIO "
                "DE INSUMOS Y MATERIALES MENORES UTILIZADOS DURANTE EL ACTO QUIRÚRGICO Y "
                "ESTÁ EXPRESAMENTE CONTEMPLADO EN EL ANEXO TARIFARIO INSTITUCIONAL." + CIERRE_STD
            ),
        },
    },
    # -------------------------------------------------------------------------
    # GRUPO 2 — SOPORTES (SO) — 10 conceptos
    # -------------------------------------------------------------------------
    "SO": {
        "SO-G01": {
            "titulo": "HISTORIA CLÍNICA INTEGRAL APORTADA — RES. 1995/1999",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE SOPORTE EN HISTORIA CLÍNICA, DADO "
                "QUE LA HISTORIA CLÍNICA INTEGRAL DEL USUARIO FUE EFECTIVAMENTE REMITIDA "
                "COMO PARTE DE LOS SOPORTES DE LA CUENTA DE COBRO, EN CUMPLIMIENTO DE LA "
                "RESOLUCIÓN 1995 DE 1999 (PRINCIPIOS DE INTEGRALIDAD, SECUENCIALIDAD, "
                "RACIONALIDAD CIENTÍFICA Y OPORTUNIDAD), DE LA RESOLUCIÓN 839 DE 2017 Y "
                "DEL ANEXO TÉCNICO No. 5 DE LA RESOLUCIÓN 3047 DE 2008. LA HISTORIA "
                "CLÍNICA CONSTITUYE UN DOCUMENTO ÚNICO E INDIVISIBLE CUYAS PARTES SON "
                "COMPLEMENTARIAS Y CONFORMAN UN TODO PROBATORIO INDIVISIBLE. EL SOPORTE "
                "ESPECÍFICO QUE ECHA DE MENOS LA AUDITORÍA DE {PAGADOR} SE ENCUENTRA "
                "EFECTIVAMENTE INCORPORADO EN LOS ARCHIVOS APORTADOS EN FOLIO/SECCIÓN "
                "DISTINTA A LA REVISADA. SE SUGIERE LA VERIFICACIÓN INTEGRAL DEL "
                "EXPEDIENTE EN APLICACIÓN DEL PRINCIPIO DE CARGA DINÁMICA DE LA PRUEBA "
                "(CSJ — SC-1990 DE 2024)." + CIERRE_STD
            ),
        },
        "SO-G02": {
            "titulo": "SOPORTES MÍNIMOS COMPLETOS — RES. 3047/2008 + RES. 2284/2023",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA FALTA DE SOPORTES DE FACTURACIÓN, DADO QUE LA "
                "FACTURA FUE RADICADA ACOMPAÑADA DE LA TOTALIDAD DE LOS SOPORTES MÍNIMOS "
                "EXIGIDOS POR EL ANEXO TÉCNICO No. 5 DE LA RESOLUCIÓN 3047 DE 2008 "
                "(ADICIONADA Y MODIFICADA POR LA RES. 4331/2012), EL ANEXO TÉCNICO No. 1 "
                "DE LA RESOLUCIÓN 2284 DE 2023 Y EL DECRETO 4747 DE 2007. LA FACTURACIÓN "
                "INCORPORA: (I) FACTURA ELECTRÓNICA DE VENTA; (II) AUTORIZACIÓN PREVIA; "
                "(III) DOCUMENTO DE IDENTIDAD; (IV) EPICRISIS U HOJA DE URGENCIAS; "
                "(V) HOJA DE ADMINISTRACIÓN DE MEDICAMENTOS; (VI) APOYO DIAGNÓSTICO; "
                "(VII) DESCRIPCIÓN QUIRÚRGICA Y REGISTRO ANESTÉSICO; (VIII) RIPS JSON "
                "RES. 2275/2023; (IX) CUV DEL MINSALUD." + CIERRE_STD
            ),
        },
        "SO-G03": {
            "titulo": "AUTORIZACIÓN PREVIA — TEORÍA DE LOS ACTOS PROPIOS",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE AUTORIZACIÓN PARA EL SERVICIO "
                "PRESTADO, DADO QUE EL HUS CUENTA CON LA AUTORIZACIÓN PREVIA EXPEDIDA POR "
                "{PAGADOR} A TRAVÉS DE SUS CANALES OFICIALES PARA AUTORIZACIONES. UNA VEZ "
                "EMITIDA LA AUTORIZACIÓN, NO RESULTA PROCEDENTE OBJETAR EL SERVICIO POR "
                "ESTA CAUSAL, EN APLICACIÓN DE LA TEORÍA DE LOS ACTOS PROPIOS (VENIRE "
                "CONTRA FACTUM PROPRIUM NON VALET) DESARROLLADA POR LA CORTE SUPREMA DE "
                "JUSTICIA EN SENTENCIA SC1182-2016 Y DEL ARTÍCULO 1603 DEL CÓDIGO CIVIL "
                "(BUENA FE CONTRACTUAL). PARA SERVICIOS DE ATENCIÓN INICIAL DE URGENCIAS, "
                "NO SE REQUIERE AUTORIZACIÓN PREVIA CONFORME AL ARTÍCULO 2.5.3.2.6 DEL "
                "DECRETO 780 DE 2016." + CIERRE_STD
            ),
        },
        "SO-G04": {
            "titulo": "DESCRIPCIÓN QUIRÚRGICA Y REGISTRO ANESTÉSICO APORTADOS",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE DESCRIPCIÓN QUIRÚRGICA Y/O REGISTRO "
                "ANESTÉSICO, DADO QUE AMBOS DOCUMENTOS FUERON EFECTIVAMENTE REMITIDOS COMO "
                "PARTE DE LOS SOPORTES DE LA CUENTA DE COBRO, EN CUMPLIMIENTO DEL ANEXO "
                "TÉCNICO No. 5 DE LA RESOLUCIÓN 3047 DE 2008, DEL DECRETO 4747 DE 2007 Y "
                "DE LA RESOLUCIÓN 1995 DE 1999 (ART. 14). LA DESCRIPCIÓN QUIRÚRGICA ESTÁ "
                "SUSCRITA POR EL CIRUJANO TRATANTE CON SU REGISTRO MÉDICO VIGENTE, "
                "CONTIENE TÉCNICA OPERATORIA, HALLAZGOS, MATERIALES, DURACIÓN Y EVENTOS. "
                "EL REGISTRO ANESTÉSICO INCLUYE SIGNOS VITALES INTRAOPERATORIOS, "
                "MEDICAMENTOS, TÉCNICA ANESTÉSICA Y CLASIFICACIÓN ASA, SUSCRITO POR EL "
                "ANESTESIÓLOGO TRATANTE." + CIERRE_STD
            ),
        },
        "SO-G05": {
            "titulo": "ÓRDENES MÉDICAS Y PRESCRIPCIÓN FACULTATIVA — LEY 23/1981",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE ORDEN MÉDICA O PRESCRIPCIÓN "
                "FACULTATIVA, DADO QUE LA ORDEN MÉDICA SE ENCUENTRA INCORPORADA EN LA "
                "HISTORIA CLÍNICA APORTADA, FUE SUSCRITA POR EL MÉDICO TRATANTE CON SU "
                "REGISTRO MÉDICO VIGENTE EN LA FECHA Y HORA PRECEDENTES A LA EJECUCIÓN "
                "DEL PROCEDIMIENTO, Y CONTIENE LA IDENTIFICACIÓN DEL PACIENTE, FECHA Y "
                "HORA, DESCRIPCIÓN DEL PROCEDIMIENTO PRESCRITO, JUSTIFICACIÓN CLÍNICA Y "
                "FIRMA-REGISTRO PROFESIONAL, CONFORME AL ARTÍCULO 7° DE LA RESOLUCIÓN "
                "1995 DE 1999 Y A LA RESOLUCIÓN 839 DE 2017. LA LEY 23 DE 1981 (CÓDIGO "
                "DE ÉTICA MÉDICA) Y EL ARTÍCULO 17 DE LA LEY 1751 DE 2015 GARANTIZAN LA "
                "AUTONOMÍA PROFESIONAL DEL MÉDICO TRATANTE." + CIERRE_STD
            ),
        },
        "SO-G06": {
            "titulo": "EPICRISIS — CONTENIDO COMPLETO Y SUFICIENTE",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA O DEFICIENCIA DE EPICRISIS, DADO QUE "
                "LA EPICRISIS REMITIDA CONTIENE LA TOTALIDAD DE ELEMENTOS EXIGIDOS POR EL "
                "ARTÍCULO 17 DE LA RESOLUCIÓN 1995 DE 1999: IDENTIFICACIÓN COMPLETA DEL "
                "USUARIO, MOTIVO DE INGRESO, RESUMEN DE LA EVOLUCIÓN CLÍNICA, "
                "DIAGNÓSTICOS PRINCIPAL Y SECUNDARIOS EN CÓDIGOS CIE-10, TRATAMIENTOS "
                "REALIZADOS, CONDICIÓN DEL PACIENTE AL EGRESO, PLAN DE MANEJO POSTERIOR Y "
                "FIRMA DEL MÉDICO TRATANTE CON SU REGISTRO MÉDICO. LA EPICRISIS RESUME "
                "ÍNTEGRAMENTE LA ATENCIÓN PRESTADA Y CONSTITUYE EL DOCUMENTO PRINCIPAL DE "
                "SOPORTE DEL EVENTO HOSPITALARIO." + CIERRE_STD
            ),
        },
        "SO-G07": {
            "titulo": "HOJA DE ADMINISTRACIÓN DE MEDICAMENTOS — RES. 1995/1999 ART. 11",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE HOJA DE ADMINISTRACIÓN DE "
                "MEDICAMENTOS O INCONSISTENCIA ENTRE MEDICAMENTOS FACTURADOS Y ADMINISTRADOS, "
                "DADO QUE LA HOJA DE ADMINISTRACIÓN DE MEDICAMENTOS HACE PARTE INTEGRAL "
                "DE LA HISTORIA CLÍNICA APORTADA, SE ENCUENTRA DILIGENCIADA POR EL "
                "PERSONAL DE ENFERMERÍA AUTORIZADO Y CONTIENE LA TRAZABILIDAD COMPLETA "
                "DE PRESCRIPCIÓN, DISPENSACIÓN Y ADMINISTRACIÓN DE CADA MEDICAMENTO "
                "FACTURADO, CON FECHA, HORA, DOSIS, VÍA, FIRMA Y REGISTRO PROFESIONAL "
                "DE QUIEN ADMINISTRA, CONFORME AL ARTÍCULO 11 DE LA RESOLUCIÓN 1995 DE "
                "1999. LOS MEDICAMENTOS FACTURADOS COINCIDEN EXACTAMENTE CON LOS "
                "REGISTRADOS COMO ADMINISTRADOS." + CIERRE_STD
            ),
        },
        "SO-G08": {
            "titulo": "RESULTADOS DE APOYO DIAGNÓSTICO APORTADOS",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE RESULTADOS DE EXÁMENES DE "
                "LABORATORIO, IMÁGENES DIAGNÓSTICAS O AYUDAS DIAGNÓSTICAS FACTURADAS, "
                "DADO QUE LOS RESULTADOS DE TODAS LAS AYUDAS DIAGNÓSTICAS PRESCRITAS Y "
                "FACTURADAS SE ENCUENTRAN INCORPORADOS EN LA HISTORIA CLÍNICA REMITIDA "
                "O REPOSAN EN EL SISTEMA DE INFORMACIÓN DE APOYO DIAGNÓSTICO DEL HUS "
                "(CONSULTABLE POR EL EQUIPO AUDITOR EN LA SEDE INSTITUCIONAL). LA "
                "INTEGRALIDAD DE LA HISTORIA CLÍNICA EXIGIDA POR LA RESOLUCIÓN 1995 DE "
                "1999 GARANTIZA QUE TODOS LOS REPORTES SON ACCESIBLES DENTRO DEL "
                "EXPEDIENTE." + CIERRE_STD
            ),
        },
        "SO-G09": {
            "titulo": "CARGA DINÁMICA DE LA PRUEBA — CSJ SC-1990 DE 2024",
            "texto": (
                ENCABEZADO_STD + "OBJECIÓN GENÉRICA SOBRE INSUFICIENCIA DE SOPORTES "
                "DOCUMENTALES, DADO QUE EL HUS APORTÓ LA TOTALIDAD DE LOS SOPORTES "
                "EXIGIDOS POR LA NORMATIVIDAD VIGENTE Y QUE, EN APLICACIÓN DEL PRINCIPIO "
                "DE CARGA DINÁMICA DE LA PRUEBA DESARROLLADO POR LA CORTE SUPREMA DE "
                "JUSTICIA EN SENTENCIA SC-1990 DE 2024, CORRESPONDE A {PAGADOR} INDICAR "
                "CON PRECISIÓN CUÁL ES EL SOPORTE DOCUMENTAL ESPECÍFICO QUE ECHA DE "
                "MENOS Y CUÁL ES LA NORMA VIGENTE QUE LO HACE EXIGIBLE. LA OBJECIÓN "
                'GENÉRICA "FALTAN SOPORTES" SIN INDIVIDUALIZACIÓN VIOLA EL DEBIDO '
                "PROCESO (ART. 29 C.P.) E IMPIDE EL DERECHO DE CONTRADICCIÓN." + CIERRE_STD
            ),
        },
        "SO-G10": {
            "titulo": "INTEGRALIDAD E INDIVISIBILIDAD DE LA HISTORIA CLÍNICA",
            "texto": (
                ENCABEZADO_STD + "OBJECIÓN POR PRESUNTA AUSENCIA DE DOCUMENTO ESPECÍFICO "
                "DENTRO DE LA HISTORIA CLÍNICA, DADO QUE LA HISTORIA CLÍNICA CONSTITUYE "
                "UN DOCUMENTO ÚNICO E INDIVISIBLE CONFORME AL ARTÍCULO 1° DE LA "
                'RESOLUCIÓN 1995 DE 1999 ("REGISTRO OBLIGATORIO DE LAS CONDICIONES DE '
                "SALUD DEL PACIENTE… ES UN DOCUMENTO PRIVADO, OBLIGATORIO Y SOMETIDO A "
                "RESERVA, EN EL CUAL SE REGISTRAN CRONOLÓGICAMENTE LAS CONDICIONES DE "
                "SALUD DEL PACIENTE, LOS ACTOS MÉDICOS Y LOS DEMÁS PROCEDIMIENTOS "
                'EJECUTADOS POR EL EQUIPO DE SALUD QUE INTERVIENE EN SU ATENCIÓN"). EL '
                "PRESUNTO SOPORTE FALTANTE PUEDE ENCONTRARSE EN FOLIO DISTINTO AL "
                "REVISADO O EN OTRA SECCIÓN DEL EXPEDIENTE QUE EL EQUIPO AUDITOR NO HA "
                "VERIFICADO INTEGRALMENTE." + CIERRE_STD
            ),
        },
    },
    # -------------------------------------------------------------------------
    # GRUPO 3 — COBERTURA (CO) — 10 conceptos
    # -------------------------------------------------------------------------
    "CO": {
        "CO-G01": {
            "titulo": "SERVICIO COBIJADO POR PBS — RES. 2641/2024",
            "texto": (
                ENCABEZADO_STD + "SERVICIO PRESUNTAMENTE NO COBIJADO POR EL PLAN DE "
                "BENEFICIOS, DADO QUE EL ÍTEM FACTURADO CORRESPONDE A UN SERVICIO "
                "INCLUIDO EN EL PLAN DE BENEFICIOS EN SALUD CON CARGO A LA UPC, "
                "EXPRESAMENTE REGULADO POR LA RESOLUCIÓN 2641 DE 2024 DEL MINISTERIO "
                "DE SALUD Y PROTECCIÓN SOCIAL. SI LA OBJECIÓN DE {PAGADOR} INVOCA UNA "
                "EXCLUSIÓN ESPECÍFICA, CORRESPONDE AL PAGADOR APORTAR LOS FUNDAMENTOS "
                "NORMATIVOS Y FÁCTICOS QUE SUSTENTEN DICHA EXCLUSIÓN, EN APLICACIÓN "
                "DEL PRINCIPIO DE CARGA DINÁMICA DE LA PRUEBA. LA LEY 1751 DE 2015 "
                "GARANTIZA LA INTEGRALIDAD DEL DERECHO FUNDAMENTAL A LA SALUD Y "
                "PROHÍBE FRAGMENTAR LA ATENCIÓN POR RAZONES DE COBERTURA." + CIERRE_STD
            ),
        },
        "CO-G02": {
            "titulo": "ATENCIÓN INICIAL DE URGENCIAS SIN AUTORIZACIÓN — ART. 168 LEY 100",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE AUTORIZACIÓN PREVIA EN ATENCIÓN "
                "INICIAL DE URGENCIAS, DADO QUE EL SERVICIO PRESTADO CORRESPONDE A LA "
                "ATENCIÓN INICIAL DE URGENCIAS DEFINIDA EN EL ARTÍCULO 2.5.3.2.6 DEL "
                "DECRETO 780 DE 2016, LA CUAL POR SU NATURALEZA NO REQUIERE AUTORIZACIÓN "
                "PREVIA Y ES DE OBLIGATORIA PRESTACIÓN POR PARTE DEL HUS CONFORME AL "
                "ARTÍCULO 168 DE LA LEY 100 DE 1993, AL ARTÍCULO 10 DE LA LEY ESTATUTARIA "
                "1751 DE 2015 Y A LA JURISPRUDENCIA REITERADA DE LA CORTE CONSTITUCIONAL "
                "(T-760/2008, C-313/2014). LA EXIGENCIA DE AUTORIZACIÓN PREVIA EN "
                "ATENCIÓN INICIAL DE URGENCIAS CONTRAVIENE EL PRINCIPIO DE INTEGRALIDAD "
                "(ART. 8 LEY 1751/2015) Y CONSTITUYE UNA BARRERA DE ACCESO PROHIBIDA POR "
                "LA LEY 1438 DE 2011." + CIERRE_STD
            ),
        },
        "CO-G03": {
            "titulo": "ESTANCIA HOSPITALARIA JUSTIFICADA — AUTONOMÍA MÉDICA",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA ESTANCIA HOSPITALARIA INJUSTIFICADA O "
                "PROLONGADA, DADO QUE LA DURACIÓN DE LA HOSPITALIZACIÓN OBEDECIÓ A LA "
                "EVOLUCIÓN CLÍNICA DEL PACIENTE Y A LOS CRITERIOS MÉDICOS DE EGRESO "
                "DOCUMENTADOS EN LAS NOTAS DE EVOLUCIÓN DIARIAS DE LA HISTORIA CLÍNICA. "
                "LA AUTONOMÍA PROFESIONAL DEL MÉDICO TRATANTE PARA DEFINIR LA "
                "OPORTUNIDAD DE EGRESO ESTÁ AMPARADA POR EL ARTÍCULO 17 DE LA LEY "
                "ESTATUTARIA 1751 DE 2015. CUALQUIER PROLONGACIÓN DERIVADA DE DEMORA EN "
                "AUTORIZACIÓN DE TRASLADO, NEGATIVA DE COBERTURA POR PARTE DE {PAGADOR} "
                "O FALTA DE RESPUESTA OPORTUNA NO ES IMPUTABLE AL HUS, EN APLICACIÓN DE "
                "LA OBLIGACIÓN BILATERAL DE COLABORACIÓN DERIVADA DEL ARTÍCULO 1603 DEL "
                "CÓDIGO CIVIL Y DEL ART. 871 DEL CÓDIGO DE COMERCIO." + CIERRE_STD
            ),
        },
        "CO-G04": {
            "titulo": "AFILIACIÓN ACTIVA — VERIFICACIÓN BDUA AL MOMENTO DE LA ATENCIÓN",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE COBERTURA POR NO AFILIACIÓN "
                "ACTIVA DEL USUARIO A {PAGADOR}, DADO QUE LA VERIFICACIÓN DE DERECHOS "
                "DEL PACIENTE FUE REALIZADA AL MOMENTO DE LA ATENCIÓN MEDIANTE LA "
                "CONSULTA DE LA BASE DE DATOS ÚNICA DE AFILIADOS (BDUA) DE LA ADRES Y/O "
                "DE LAS PLATAFORMAS HABILITADAS POR EL PAGADOR, ENCONTRÁNDOSE EL "
                "USUARIO EN ESTADO ACTIVO. EL HUS APORTA: COPIA DEL DOCUMENTO DE "
                "IDENTIDAD, AUTORIZACIÓN EXPEDIDA POR {PAGADOR} CUANDO APLIQUE, Y "
                "FACTURA ELECTRÓNICA EMITIDA A NOMBRE DEL PAGADOR. UNA VEZ EL PAGADOR "
                "EXPIDIÓ LA AUTORIZACIÓN O LA ATENCIÓN SE PRESTÓ COMO URGENCIA, EL "
                "ASEGURAMIENTO QUEDÓ MATERIALMENTE RECONOCIDO Y NO RESULTA PROCEDENTE "
                "SU REVOCATORIA EX-POST (TEORÍA DE LOS ACTOS PROPIOS — CSJ "
                "SC1182-2016)." + CIERRE_STD
            ),
        },
        "CO-G05": {
            "titulo": "INTEGRALIDAD DE LA ATENCIÓN — ART. 8 LEY 1751/2015",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO COBERTURA DE SERVICIOS ACCESORIOS O "
                "COMPLEMENTARIOS AL EVENTO PRINCIPAL, DADO QUE EL PRINCIPIO DE "
                "INTEGRALIDAD CONSAGRADO EN EL ARTÍCULO 8° DE LA LEY ESTATUTARIA 1751 "
                'DE 2015 ESTABLECE: "LOS SERVICIOS DE SALUD DEBEN PRESTARSE DE MANERA '
                "COMPLETA PARA PREVENIR, PALIAR O CURAR LA ENFERMEDAD, CON INDEPENDENCIA "
                "DEL ORIGEN DE LA ENFERMEDAD O CONDICIÓN DE SALUD, DEL SISTEMA DE "
                'PROVISIÓN, CUBRIMIENTO O FINANCIACIÓN DEFINIDO POR EL LEGISLADOR". '
                "LOS SERVICIOS ACCESORIOS FACTURADOS (LABORATORIOS DE CONTROL, AYUDAS "
                "DIAGNÓSTICAS, INTERCONSULTAS, MEDICAMENTOS, INSUMOS) RESULTARON "
                "CLÍNICAMENTE INDISPENSABLES, CONFORME AL CRITERIO DEL MÉDICO TRATANTE "
                "EN EJERCICIO DE SU AUTONOMÍA PROFESIONAL (ART. 17 LEY 1751/2015). LA "
                "CORTE CONSTITUCIONAL EN T-760/2008 Y C-313/2014 PROHÍBE FRAGMENTAR LA "
                "ATENCIÓN POR RAZONES DE COBERTURA." + CIERRE_STD
            ),
        },
        "CO-G06": {
            "titulo": "COBERTURA DE ALTO COSTO Y ENFERMEDADES HUÉRFANAS",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO COBERTURA DE PROCEDIMIENTO, MEDICAMENTO O "
                "INSUMO DE ALTO COSTO O ENFERMEDAD HUÉRFANA, DADO QUE LA ATENCIÓN DE "
                "ENFERMEDADES DE ALTO COSTO Y HUÉRFANAS HACE PARTE INTEGRAL DEL PLAN DE "
                "BENEFICIOS EN SALUD CON CARGO A LA UPC CONFORME A LA LEY 1392 DE 2010 "
                "(ENFERMEDADES HUÉRFANAS), A LA LEY 1751 DE 2015 (PRINCIPIO DE "
                "INTEGRALIDAD) Y A LA CUENTA DE ALTO COSTO. LA ATENCIÓN PRESTADA POR EL "
                "HUS CORRESPONDE A UNA INDICACIÓN DEBIDAMENTE SUSTENTADA EN LA HISTORIA "
                "CLÍNICA POR EL MÉDICO TRATANTE EN EJERCICIO DE SU AUTONOMÍA "
                "PROFESIONAL (ART. 17 LEY 1751/2015), Y LOS SERVICIOS REPORTADOS A LA "
                "CUENTA DE ALTO COSTO SE ENCUENTRAN EN ESTADO ACTIVO." + CIERRE_STD
            ),
        },
        "CO-G07": {
            "titulo": "PERIODO DE CARENCIA — INAPLICABLE EN URGENCIA Y EVENTO AGUDO",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO COBERTURA POR PERÍODO DE CARENCIA O "
                "PRE-EXISTENCIA, DADO QUE EN MATERIA DE SEGURIDAD SOCIAL EN SALUD "
                "(SGSSS) NO EXISTEN PERIODOS DE CARENCIA NI EXCLUSIONES POR "
                "PRE-EXISTENCIAS PARA AFILIADOS AL RÉGIMEN CONTRIBUTIVO O SUBSIDIADO, "
                "CONFORME AL ARTÍCULO 164 DE LA LEY 100 DE 1993 (MODIFICADO POR LA LEY "
                "1438 DE 2011) Y A LA LEY ESTATUTARIA 1751 DE 2015 ART. 6 LITERAL d "
                "(NO DISCRIMINACIÓN). LAS ATENCIONES DE URGENCIAS Y LOS EVENTOS AGUDOS "
                "SON DE OBLIGATORIA COBERTURA INMEDIATA SIN PERIODO DE CARENCIA. LA "
                "OBJECIÓN DE {PAGADOR} POR CARENCIA O PRE-EXISTENCIA ES INOPONIBLE AL "
                "PRESTADOR Y ES SANCIONABLE POR LA SUPERINTENDENCIA NACIONAL DE "
                "SALUD." + CIERRE_STD
            ),
        },
        "CO-G08": {
            "titulo": "TRASLADO ASISTENCIAL — INTEGRALIDAD + RES. 1043/2006",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO COBERTURA DE TRASLADO ASISTENCIAL POR "
                "AMBULANCIA, DADO QUE EL TRASLADO ASISTENCIAL HACE PARTE INTEGRAL DEL "
                "PLAN DE BENEFICIOS EN SALUD CUANDO ES PRESCRITO POR EL MÉDICO TRATANTE "
                "POR RAZÓN DE LA EVOLUCIÓN CLÍNICA DEL PACIENTE Y LA NECESIDAD DE "
                "ATENCIÓN ESPECIALIZADA, CONFORME AL ART. 11 LITERAL g DE LA LEY 1562 "
                "DE 2012 (GASTOS DE TRASLADO EN CONDICIONES NORMALES NECESARIOS PARA LA "
                "PRESTACIÓN DE SERVICIOS) Y A LA RESOLUCIÓN 1043 DE 2006. EL TRASLADO "
                "FACTURADO CUENTA CON LA ORDEN MÉDICA, EL FORMATO DE REMISIÓN Y LA "
                "AUTORIZACIÓN DE {PAGADOR} CUANDO APLIQUE. LA TARIFA APLICADA "
                "CORRESPONDE A LA RESOLUCIÓN INSTITUCIONAL HUS VIGENTE." + CIERRE_STD
            ),
        },
        "CO-G09": {
            "titulo": "INSUMOS Y DISPOSITIVOS — COBERTURA POR INTEGRALIDAD",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO COBERTURA DE INSUMOS, DISPOSITIVOS MÉDICOS "
                "O MATERIALES UTILIZADOS DURANTE EL PROCEDIMIENTO, DADO QUE LA "
                "COBERTURA DE INSUMOS Y DISPOSITIVOS INDISPENSABLES PARA LA EJECUCIÓN "
                "DEL PROCEDIMIENTO QUIRÚRGICO O TERAPÉUTICO ESTÁ COMPRENDIDA POR EL "
                "PRINCIPIO DE INTEGRALIDAD (ART. 8 LEY 1751/2015) Y POR LA RESOLUCIÓN "
                "2641 DE 2024 (PBS). LOS INSUMOS FACTURADOS FUERON EFECTIVAMENTE "
                "UTILIZADOS DURANTE LA INTERVENCIÓN, ESTÁN REGISTRADOS EN LA "
                "DESCRIPCIÓN QUIRÚRGICA Y/O EN LA HOJA DE GASTOS QUIRÚRGICOS, Y SON "
                "CLÍNICAMENTE INDISPENSABLES SEGÚN LAS GUÍAS DE PRÁCTICA CLÍNICA "
                "VIGENTES." + CIERRE_STD
            ),
        },
        "CO-G10": {
            "titulo": "POBLACIONES ESPECIALES — INTEGRALIDAD REFORZADA",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO COBERTURA EN ATENCIÓN A POBLACIONES "
                "ESPECIALES (MENORES, GESTANTES, ADULTOS MAYORES, PERSONAS CON "
                "DISCAPACIDAD, VÍCTIMAS DEL CONFLICTO, PUEBLOS INDÍGENAS, "
                "AFROCOLOMBIANOS, LGTBI, VÍCTIMAS DE VIOLENCIA), DADO QUE ESTAS "
                "POBLACIONES GOZAN DE INTEGRALIDAD REFORZADA POR DISPOSICIÓN "
                "CONSTITUCIONAL Y LEGAL: ART. 44 C.P. (DERECHOS DE LOS NIÑOS — "
                "PRIMACÍA), ART. 43 C.P. (PROTECCIÓN ESPECIAL A LA MUJER EMBARAZADA), "
                "ART. 46 C.P. (ADULTO MAYOR), LEY 1448 DE 2011 (VÍCTIMAS), LEY 1346 DE "
                "2009 Y LEY 1618 DE 2013 (DISCAPACIDAD), AUTO 092/2008 CORTE "
                "CONSTITUCIONAL (MUJERES EN DESPLAZAMIENTO). LA OBJECIÓN DE {PAGADOR} "
                "DESCONOCE ESTOS MANDATOS." + CIERRE_STD
            ),
        },
    },
    # -------------------------------------------------------------------------
    # GRUPO 4 — FACTURACIÓN (FA) — 10 conceptos
    # -------------------------------------------------------------------------
    "FA": {
        "FA-G01": {
            "titulo": "FACTURA ELECTRÓNICA — ART. 617 ET + RES. DIAN 165/2023",
            "texto": (
                ENCABEZADO_STD + "PRESUNTOS DEFECTOS FORMALES EN LA FACTURACIÓN, DADO "
                "QUE LA FACTURA ELECTRÓNICA DE VENTA FUE EXPEDIDA EN ESTRICTO "
                "CUMPLIMIENTO DE: (I) ARTÍCULO 617 DEL ESTATUTO TRIBUTARIO; "
                "(II) RESOLUCIÓN DIAN 165 DE 2023 (ARTÍCULO 11 Y ANEXO TÉCNICO 1.9); "
                "(III) RESOLUCIÓN 2275 DE 2023 (FEV EN EL SECTOR SALUD); "
                "(IV) RESOLUCIÓN 2335 DE 2023 (RIPS). LA FACTURA FUE DENOMINADA "
                "EXPRESAMENTE COMO FACTURA ELECTRÓNICA DE VENTA, EMITIDA A NOMBRE DE "
                "{PAGADOR}, IDENTIFICA AL PRESTADOR HOSPITAL UNIVERSITARIO DE "
                "SANTANDER (NIT 900.006.037-4), TIENE NUMERACIÓN CONSECUTIVA "
                "AUTORIZADA POR LA DIAN, FECHA DE EXPEDICIÓN, DESCRIPCIÓN DETALLADA DE "
                "LOS SERVICIOS, VALOR UNITARIO Y TOTAL, Y FUE VALIDADA POR LA DIAN CON "
                "SU RESPECTIVO CUFE." + CIERRE_STD
            ),
        },
        "FA-G02": {
            "titulo": "RADICACIÓN OPORTUNA — 22 DÍAS HÁBILES ART. 14 RES. 2275/2023",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA RADICACIÓN EXTEMPORÁNEA DE LA FACTURA, DADO "
                "QUE EL RADICADO SE REALIZÓ DENTRO DEL TÉRMINO DE 22 DÍAS HÁBILES "
                'ESTABLECIDOS EN EL ARTÍCULO 14 DE LA RESOLUCIÓN 2275 DE 2023: "LOS '
                "FACTURADORES ELECTRÓNICOS DEL SECTOR SALUD DISPONEN DE VEINTIDÓS (22) "
                "DÍAS HÁBILES, CONTADOS A PARTIR DE LA FECHA DE EXPEDICIÓN DE LA "
                "FACTURA ELECTRÓNICA DE VENTA CON VALIDACIÓN PREVIA DE LA UNIDAD "
                "ADMINISTRATIVA ESPECIAL DIRECCIÓN DE IMPUESTOS Y ADUANAS NACIONALES "
                "- DIAN, PARA LA RADICACIÓN ANTE LAS ENTIDADES RESPONSABLES DE PAGO O "
                'DEMÁS PAGADORES". EL ACUSE DE RECIBO ELECTRÓNICO Y EL CUV '
                "CONSTITUYEN PRUEBA INCONTROVERTIBLE DE LA OPORTUNA RADICACIÓN." + CIERRE_STD
            ),
        },
        "FA-G03": {
            "titulo": "RIPS JSON — RES. 2275/2023 + RES. 2335/2023",
            "texto": (
                ENCABEZADO_STD + "PRESUNTAS INCONSISTENCIAS EN LOS REGISTROS "
                "INDIVIDUALES DE PRESTACIÓN DE SERVICIOS DE SALUD (RIPS), DADO QUE LOS "
                "RIPS REMITIDOS FUERON GENERADOS, VALIDADOS Y ENVIADOS EN ESTRICTA "
                "CONFORMIDAD CON LA RESOLUCIÓN 2275 DEL 28 DE DICIEMBRE DE 2023 Y LA "
                "RESOLUCIÓN 2335 DE 2023. LOS ARCHIVOS RIPS FUERON GENERADOS EN "
                "FORMATO JSON CONFORME AL ANEXO TÉCNICO 1, ESTÁN ESTRUCTURADOS "
                "CORRECTAMENTE Y SON CONSISTENTES CON LA FACTURA ELECTRÓNICA Y LA "
                "HISTORIA CLÍNICA. EL CÓDIGO ÚNICO DE VALIDACIÓN (CUV) GENERADO POR EL "
                "VALIDADOR DEL MINSALUD CERTIFICA LA CONFORMIDAD ESTRUCTURAL. LA "
                "AUDITORÍA DE {PAGADOR} DEBE FUNDAMENTAR ESPECÍFICAMENTE CUÁL CAMPO ES "
                "INCONSISTENTE Y CONTRASTARLO CON LA HISTORIA CLÍNICA." + CIERRE_STD
            ),
        },
        "FA-G04": {
            "titulo": "CERTIFICACIÓN APORTES SEGURIDAD SOCIAL Y PARAFISCALES",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA AUSENCIA DE CERTIFICACIÓN DE APORTES AL "
                "SISTEMA DE SEGURIDAD SOCIAL Y PARAFISCALES, DADO QUE EL HUS APORTA LA "
                "CERTIFICACIÓN VIGENTE DE CUMPLIMIENTO DE LOS PAGOS AL SISTEMA DE "
                "SEGURIDAD SOCIAL EN SALUD, PENSIONES, RIESGOS LABORALES Y APORTES "
                "PARAFISCALES (SENA, ICBF, CAJAS DE COMPENSACIÓN), SUSCRITA POR EL "
                "REVISOR FISCAL O EL REPRESENTANTE LEGAL, EN CUMPLIMIENTO DEL ARTÍCULO "
                "50 DE LA LEY 789 DE 2002, LA LEY 797 DE 2003, EL DECRETO 510 DE 2003 "
                "Y EL ARTÍCULO 23 DE LA LEY 1150 DE 2007. EN CASO DE QUE LA AUDITORÍA "
                "NO HUBIERE LOCALIZADO ESTOS DOCUMENTOS, EL HUS LOS REMITE NUEVAMENTE "
                "COMO ANEXO." + CIERRE_STD
            ),
        },
        "FA-G05": {
            "titulo": "TÉRMINOS DE GLOSA — ART. 57 LEY 1438/2011 + ANEXO 6 RES. 3047/2008",
            "texto": (
                ENCABEZADO_STD + "OBJECIÓN GENÉRICA SIN TIPIFICACIÓN ESPECÍFICA O "
                "FORMULADA POR FUERA DE LOS TÉRMINOS LEGALES, DADO QUE EL TRÁMITE DE "
                "GLOSAS Y DEVOLUCIONES SE RIGE POR EL ARTÍCULO 57 DE LA LEY 1438 DE "
                "2011, EL DECRETO 441 DE 2022, EL ANEXO TÉCNICO No. 6 DE LA RESOLUCIÓN "
                "3047 DE 2008 (MANUAL ÚNICO DE GLOSAS, DEVOLUCIONES Y RESPUESTAS) CON "
                "LAS MODIFICACIONES DE LA RES. 416/2009 Y RES. 4331/2012, Y EL ANEXO "
                "TÉCNICO No. 3 DE LA RESOLUCIÓN 2284 DE 2023. LA GLOSA NO IDENTIFICA "
                "CON PRECISIÓN LA CAUSAL Y SUBCAUSAL ESPECÍFICA, LO QUE IMPIDE EJERCER "
                "PLENAMENTE EL DERECHO DE CONTRADICCIÓN. EL ART. 57 LEY 1438 "
                "ESTABLECE: 30 DÍAS HÁBILES PARA FORMULAR LA GLOSA, 15 DÍAS HÁBILES "
                "PARA RESPONDER, 30 DÍAS HÁBILES PARA RESOLVER." + CIERRE_STD
            ),
        },
        "FA-G06": {
            "titulo": "GLOSA EXTEMPORÁNEA — PRECLUSIÓN DEL TÉRMINO ART. 57 LEY 1438",
            "texto": (
                ENCABEZADO_STD + "OBJECIÓN FORMULADA POR FUERA DEL TÉRMINO DE LOS 30 "
                "DÍAS HÁBILES SIGUIENTES A LA RADICACIÓN DE LA FACTURA, DADO QUE EL "
                'ARTÍCULO 57 DE LA LEY 1438 DE 2011 ESTABLECE: "LAS ENTIDADES '
                "RESPONSABLES DEL PAGO DE SERVICIOS DE SALUD DENTRO DE LOS TREINTA "
                "(30) DÍAS HÁBILES SIGUIENTES A LA PRESENTACIÓN DE LA FACTURA CON "
                "TODOS SUS SOPORTES, FORMULARÁN Y COMUNICARÁN A LOS PRESTADORES DE "
                "SERVICIOS DE SALUD LAS GLOSAS A CADA FACTURA, CON BASE EN LA "
                "CODIFICACIÓN Y ALCANCE DEFINIDOS EN LA NORMATIVIDAD VIGENTE. UNA VEZ "
                "FORMULADAS LAS GLOSAS A UNA FACTURA NO SE PODRÁN FORMULAR NUEVAS "
                "GLOSAS A LA MISMA FACTURA, SALVO LAS QUE SURJAN DE HECHOS NUEVOS "
                'DETECTADOS EN LA RESPUESTA DADA A LA GLOSA INICIAL". LA GLOSA '
                "EXTEMPORÁNEA NO PRODUCE EFECTOS Y SE ENTIENDE COMO ACEPTACIÓN TÁCITA "
                "DE LA FACTURA POR EL PAGADOR." + CIERRE_STD
            ),
        },
        "FA-G07": {
            "titulo": "PRECLUSIÓN DE NUEVA GLOSA SOBRE LA MISMA FACTURA",
            "texto": (
                ENCABEZADO_STD + "FORMULACIÓN DE NUEVA GLOSA SOBRE FACTURA YA "
                "PREVIAMENTE GLOSADA Y RESPONDIDA, DADO QUE EL ARTÍCULO 57 DE LA LEY "
                '1438 DE 2011 PROHÍBE EXPRESAMENTE LA REITERACIÓN DE GLOSAS: "UNA VEZ '
                "FORMULADAS LAS GLOSAS A UNA FACTURA NO SE PODRÁN FORMULAR NUEVAS "
                "GLOSAS A LA MISMA FACTURA, SALVO LAS QUE SURJAN DE HECHOS NUEVOS "
                'DETECTADOS EN LA RESPUESTA DADA A LA GLOSA INICIAL". LA GLOSA '
                "OBJETO DE LA PRESENTE RESPUESTA NO SE FUNDAMENTA EN HECHOS NUEVOS "
                "DERIVADOS DE LA RESPUESTA PREVIA DEL HUS, SINO QUE CONSTITUYE UNA "
                "REITERACIÓN PROHIBIDA POR LA LEY. ADICIONALMENTE, LA REITERACIÓN "
                "VIOLA EL PRINCIPIO DE NON BIS IN IDEM Y EL DEBIDO PROCESO (ART. 29 "
                "C.P.)." + CIERRE_STD
            ),
        },
        "FA-G08": {
            "titulo": "PAGOS COMPARTIDOS — COPAGOS Y CUOTAS MODERADORAS",
            "texto": (
                ENCABEZADO_STD + "PRESUNTO DESCUENTO DE COPAGOS O CUOTAS MODERADORAS NO "
                "RECAUDADAS, DADO QUE EL DECRETO 441 DE 2022 (Y EL ACUERDO 260 DE 2004 "
                "DEL CNSSS PARA AFILIADOS DEL CONTRIBUTIVO) ESTABLECE QUE LOS PAGOS "
                "COMPARTIDOS SE CONSIDERAN PARTE DEL PAGO AL PRESTADOR ÚNICAMENTE "
                "CUANDO EXISTE RECAUDO EFECTIVO. EL HUS NOTIFICÓ OPORTUNAMENTE A "
                "{PAGADOR} LOS CASOS DE NO RECAUDO POR EL USUARIO, CORRESPONDIENDO AL "
                "PAGADOR RECONOCER Y PAGAR DICHA SUMA Y ADELANTAR EL COBRO DIRECTAMENTE "
                "AL USUARIO. EL DESCUENTO UNILATERAL DE COPAGOS NO RECAUDADOS VIOLA EL "
                "DECRETO 441 DE 2022 Y EL ARTÍCULO 1602 DEL CÓDIGO CIVIL." + CIERRE_STD
            ),
        },
        "FA-G09": {
            "titulo": "INTERESES MORATORIOS — DECRETO 441/2022 ART. 2.5.3.4.5.7",
            "texto": (
                ENCABEZADO_STD + "OBJECIÓN POR DEMORA O RECONOCIMIENTO PARCIAL DE PAGO, "
                "DADO QUE EL HUS TIENE DERECHO AL RECONOCIMIENTO DE INTERESES "
                "MORATORIOS POR LAS SUMAS NO PAGADAS DENTRO DEL TÉRMINO LEGAL, CONFORME "
                "AL ARTÍCULO 2.5.3.4.5.7 DEL DECRETO 780 DE 2016 (SUSTITUIDO POR EL "
                "DECRETO 441 DE 2022) Y AL ARTÍCULO 884 DEL CÓDIGO DE COMERCIO "
                "(INTERÉS BANCARIO CORRIENTE INCREMENTADO EN UNA MITAD). ADICIONALMENTE, "
                "HABRÁ LUGAR A RECONOCIMIENTOS ECONÓMICOS ANTE ACCIONES DILATORIAS DEL "
                "FLUJO DE RECURSOS CONFORME AL ARTÍCULO 2.5.3.4.5.8 DEL DECRETO 441 DE "
                "2022. LA PRESENTE RESPUESTA NO IMPLICA RENUNCIA A LOS INTERESES "
                "MORATORIOS GENERADOS." + CIERRE_STD
            ),
        },
        "FA-G10": {
            "titulo": "DEBIDO PROCESO — ART. 29 C.P. + CARGA DE LA PRUEBA",
            "texto": (
                ENCABEZADO_STD + "OBJECIÓN QUE VIOLA EL DEBIDO PROCESO ADMINISTRATIVO, "
                "DADO QUE LA GLOSA NO REÚNE LOS ELEMENTOS MÍNIMOS DE TIPIFICACIÓN "
                "CAUSAL, FUNDAMENTACIÓN NORMATIVA E IDENTIFICACIÓN PRECISA DEL ÍTEM "
                "OBJETADO EXIGIDOS POR EL ANEXO TÉCNICO No. 6 DE LA RESOLUCIÓN 3047 DE "
                "2008, EL ARTÍCULO 57 DE LA LEY 1438 DE 2011 Y EL ARTÍCULO 29 DE LA "
                "CONSTITUCIÓN POLÍTICA. EL DEBIDO PROCESO ADMINISTRATIVO EXIGE QUE TODA "
                "OBJECIÓN: (I) IDENTIFIQUE LA CAUSAL ESPECÍFICA DEL MANUAL ÚNICO DE "
                "GLOSAS; (II) FUNDAMENTE NORMATIVAMENTE LA OBJECIÓN; (III) PRECISE EL "
                "ÍTEM, FECHA, USUARIO Y FACTURA AFECTADOS; (IV) PERMITA EL DERECHO DE "
                "CONTRADICCIÓN. LA GLOSA GENÉRICA O CARENTE DE FUNDAMENTACIÓN ES "
                "NULA." + CIERRE_STD
            ),
        },
    },
    # -------------------------------------------------------------------------
    # GRUPO 5 — PERTINENCIA CLÍNICA (CL) — 10 conceptos
    # -------------------------------------------------------------------------
    "CL": {
        "CL-G01": {
            "titulo": "AUTONOMÍA MÉDICA — LEY 1751/2015 ART. 17",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO PERTINENCIA CLÍNICA DEL SERVICIO PRESTADO, "
                "DADO QUE LA PRESCRIPCIÓN Y EJECUCIÓN DEL SERVICIO OBEDECIÓ AL CRITERIO "
                "DEL MÉDICO TRATANTE EN EJERCICIO DE SU AUTONOMÍA PROFESIONAL, "
                "GARANTIZADA POR EL ARTÍCULO 17 DE LA LEY ESTATUTARIA 1751 DE 2015: "
                '"SE GARANTIZA LA AUTONOMÍA DE LOS PROFESIONALES DE LA SALUD PARA '
                "ADOPTAR DECISIONES SOBRE EL DIAGNÓSTICO Y TRATAMIENTO DE LOS PACIENTES "
                'QUE TIENEN A SU CARGO". DICHA AUTONOMÍA ESTÁ TAMBIÉN AMPARADA POR EL '
                "ARTÍCULO 17 DE LA LEY 23 DE 1981 (CÓDIGO DE ÉTICA MÉDICA), LA LEY "
                "1164 DE 2007 Y RATIFICADA POR LA CORTE CONSTITUCIONAL EN SENTENCIA "
                "C-313 DE 2014. EL CUESTIONAMIENTO POR AUDITORES ADMINISTRATIVOS DE "
                "{PAGADOR} NO PUEDE PREVALECER SOBRE EL CRITERIO DEL MÉDICO TRATANTE." + CIERRE_STD
            ),
        },
        "CL-G02": {
            "titulo": "GUÍAS DE PRÁCTICA CLÍNICA + ACREDITACIÓN ICONTEC",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA INCONSISTENCIA ENTRE EL SERVICIO PRESTADO Y "
                "EL DIAGNÓSTICO O ESTÁNDAR DE PRÁCTICA, DADO QUE LA INTERVENCIÓN "
                "EJECUTADA SE ENCUENTRA ALINEADA CON LAS GUÍAS DE PRÁCTICA CLÍNICA "
                "VIGENTES DEL MINISTERIO DE SALUD Y PROTECCIÓN SOCIAL, DEL INSTITUTO DE "
                "EVALUACIÓN TECNOLÓGICA EN SALUD (IETS), CON LOS CONSENSOS DE LAS "
                "SOCIEDADES CIENTÍFICAS Y CON LOS PROTOCOLOS INSTITUCIONALES DEL HUS "
                "APROBADOS POR EL COMITÉ TÉCNICO-CIENTÍFICO INTERNO. EL HUS, "
                "INSTITUCIÓN ACREDITADA POR EL ICONTEC (ÚNICO HOSPITAL DEL NORORIENTE "
                "COLOMBIANO CON ACREDITACIÓN EN SALUD Y SELLO DE NO DISCRIMINACIÓN), "
                "CUMPLE CON LOS ESTÁNDARES DE LA RESOLUCIÓN 3100 DE 2019, EL DECRETO "
                "1011 DE 2006 Y LA LEY 1438 DE 2011." + CIERRE_STD
            ),
        },
        "CL-G03": {
            "titulo": "TIEMPOS DE OPORTUNIDAD — RES. 1552/2013 + LEY 1122/2007",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA DEMORA INJUSTIFICADA O PROLONGACIÓN INDEBIDA "
                "DE LA ATENCIÓN, DADO QUE EL HUS DA CUMPLIMIENTO A LOS TIEMPOS DE "
                "OPORTUNIDAD DEFINIDOS POR LA SUPERINTENDENCIA NACIONAL DE SALUD, POR "
                "LA RESOLUCIÓN 1552 DE 2013 Y POR EL ARTÍCULO 23 DE LA LEY 1122 DE "
                "2007. LA EVOLUCIÓN CLÍNICA DEL PACIENTE Y LOS TIEMPOS QUIRÚRGICOS, DE "
                "INTERVENCIONISMO O DE HOSPITALIZACIÓN ESTÁN DOCUMENTADOS EN LA "
                "HISTORIA CLÍNICA Y OBEDECEN A LOS CRITERIOS MÉDICO-CIENTÍFICOS DEL "
                "EQUIPO TRATANTE. CUALQUIER DEMORA DERIVADA DE LA AUTORIZACIÓN POR "
                "PARTE DE {PAGADOR} NO ES IMPUTABLE AL HUS, EN APLICACIÓN DE LA "
                "OBLIGACIÓN BILATERAL DE COLABORACIÓN (ART. 1603 CC, ART. 871 C.CO.)." + CIERRE_STD
            ),
        },
        "CL-G04": {
            "titulo": "AYUDAS DIAGNÓSTICAS PERTINENTES — AUTONOMÍA + GPC",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO PERTINENCIA DE AYUDAS DIAGNÓSTICAS, DADO "
                "QUE LAS AYUDAS DIAGNÓSTICAS PRESCRITAS (LABORATORIO CLÍNICO, IMÁGENES "
                "DIAGNÓSTICAS, PATOLOGÍA Y/U OTROS APOYOS) FUERON SOLICITADAS POR EL "
                "MÉDICO TRATANTE COMO INSUMO INDISPENSABLE PARA: (I) CONFIRMAR EL "
                "DIAGNÓSTICO INICIAL, (II) DESCARTAR DIAGNÓSTICOS DIFERENCIALES, "
                "(III) MONITOREAR LA EVOLUCIÓN DEL TRATAMIENTO O (IV) DETECTAR "
                "COMPLICACIONES, CONFORME A LA HISTORIA CLÍNICA Y A LAS GPC. LA "
                "PERTINENCIA DE LAS AYUDAS DIAGNÓSTICAS ES UN ELEMENTO ESENCIAL DEL "
                "EJERCICIO PROFESIONAL MÉDICO PROTEGIDO POR LA AUTONOMÍA DEL ART. 17 "
                "LEY 1751/2015. SU OMISIÓN HABRÍA COMPROMETIDO LA SEGURIDAD DEL "
                "PACIENTE Y EL ESTÁNDAR DE CALIDAD." + CIERRE_STD
            ),
        },
        "CL-G05": {
            "titulo": "MEDICAMENTOS PERTINENTES — PBS RES. 2641/2024 + CNPMD",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO PERTINENCIA DE MEDICAMENTOS Y/O INSUMOS "
                "APLICADOS DURANTE LA ATENCIÓN, DADO QUE LA TOTALIDAD DE LOS "
                "MEDICAMENTOS E INSUMOS FACTURADOS FUERON PRESCRITOS POR EL MÉDICO "
                "TRATANTE, ADMINISTRADOS POR EL PERSONAL DE ENFERMERÍA Y REGISTRADOS "
                "EN LA HOJA DE ADMINISTRACIÓN DE MEDICAMENTOS DE LA HISTORIA CLÍNICA. "
                "LOS MEDICAMENTOS CORRESPONDEN AL PBS REGULADO POR LA RESOLUCIÓN 2641 "
                "DE 2024 Y A LOS PRECIOS DE LA CNPMD Y SISMED. PARA MEDICAMENTOS NO "
                "INCLUIDOS EN EL PBS, EL HUS APORTA LA JUSTIFICACIÓN MÉDICA Y/O LA "
                "PRESCRIPCIÓN POR MIPRES CONFORME A LA RESOLUCIÓN 2438 DE 2018 Y SUS "
                "MODIFICACIONES." + CIERRE_STD
            ),
        },
        "CL-G06": {
            "titulo": "NIVEL DE COMPLEJIDAD ADECUADO — HABILITACIÓN HUS",
            "texto": (
                ENCABEZADO_STD + "PRESUNTO MANEJO EN NIVEL DE COMPLEJIDAD INADECUADO, "
                "DADO QUE EL HUS, COMO INSTITUCIÓN DE COMPLEJIDAD ALTA HABILITADA POR "
                "EL MINISTERIO DE SALUD (CÓDIGO REPS 6800100792) Y ACREDITADA POR EL "
                "ICONTEC, ESTÁ AUTORIZADO PARA PRESTAR EL SERVICIO FACTURADO EN LA "
                "ESPECIALIDAD CORRESPONDIENTE. LA REMISIÓN DEL PACIENTE AL HUS FUE "
                "PRECEDIDA POR LA VALORACIÓN MÉDICA QUE DETERMINÓ LA NECESIDAD DE "
                "MANEJO EN ALTA COMPLEJIDAD, O CORRESPONDE A UNA ATENCIÓN DIRECTA DE "
                "URGENCIAS QUE NO REQUIERE REFERENCIA. EL CUESTIONAMIENTO POSTERIOR "
                "POR {PAGADOR} DEL NIVEL DE COMPLEJIDAD VIOLA EL ART. 17 DE LA LEY "
                "1751/2015 Y CONSTITUYE UNA BARRERA DE ACCESO PROHIBIDA POR LA LEY "
                "1438 DE 2011." + CIERRE_STD
            ),
        },
        "CL-G07": {
            "titulo": "DUPLICIDAD APARENTE — DESAGREGACIÓN POR ESTRUCTURA TARIFARIA",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA DUPLICIDAD EN LA FACTURACIÓN DE CUPS O "
                "SERVICIOS, DADO QUE LA APARENTE DUPLICIDAD CORRESPONDE A LA "
                "DESAGREGACIÓN OBLIGATORIA EXIGIDA POR LA ESTRUCTURA TARIFARIA DEL "
                "MANUAL SOAT (DECRETO 2423 DE 1996) Y POR LAS RESOLUCIONES "
                "INSTITUCIONALES HUS, QUE SEPARAN HONORARIOS PROFESIONALES, DERECHOS "
                "DE SALA, INSUMOS, MEDICAMENTOS Y EXÁMENES DE APOYO DIAGNÓSTICO. LAS "
                "DIFERENTES LÍNEAS DE FACTURACIÓN CORRESPONDEN A COMPONENTES DISTINTOS "
                "DEL MISMO ACTO ASISTENCIAL Y NO CONSTITUYEN DUPLICIDAD. CADA LÍNEA "
                "TIENE SU CUPS O CÓDIGO ESPECÍFICO Y SU SOPORTE EN HISTORIA "
                "CLÍNICA." + CIERRE_STD
            ),
        },
        "CL-G08": {
            "titulo": "REINGRESO / COMPLICACIÓN — NUEVO EVENTO MÉDICAMENTE JUSTIFICADO",
            "texto": (
                ENCABEZADO_STD + "PRESUNTA NO PERTINENCIA DE REINGRESO O ATENCIÓN POR "
                "COMPLICACIÓN, DADO QUE EL REINGRESO O ATENCIÓN POR COMPLICACIÓN "
                "OBEDECE A LA EVOLUCIÓN CLÍNICA NATURAL DEL PACIENTE O A UNA NUEVA "
                "MORBILIDAD INDEPENDIENTE DEL EVENTO PRINCIPAL, DEBIDAMENTE DOCUMENTADA "
                "EN LA HISTORIA CLÍNICA. LA AUTONOMÍA MÉDICA (ART. 17 LEY 1751/2015) "
                "AMPARA LA DECISIÓN DEL MÉDICO TRATANTE DE READMITIR AL PACIENTE PARA "
                "GARANTIZAR LA CONTINUIDAD Y CALIDAD ASISTENCIAL. EL PRINCIPIO DE "
                "INTEGRALIDAD EXIGE QUE LA NUEVA ATENCIÓN SE PRESTE SIN BARRERAS. SI "
                "EL REINGRESO SE DEBE A FALLA EN LA ATENCIÓN PREVIA, ESTO ESTÁ "
                "DOCUMENTADO EN LA HISTORIA CLÍNICA Y NO CONSTITUYE FUNDAMENTO PARA "
                "GLOSAR." + CIERRE_STD
            ),
        },
        "CL-G09": {
            "titulo": "PROCEDIMIENTO ALTERNATIVO O MÁS ECONÓMICO — INOPONIBLE",
            "texto": (
                ENCABEZADO_STD + "OBJECIÓN POR PRESUNTA EXISTENCIA DE PROCEDIMIENTO "
                "ALTERNATIVO MÁS ECONÓMICO O MENOS INVASIVO, DADO QUE LA SELECCIÓN DE "
                "LA TÉCNICA QUIRÚRGICA O TERAPÉUTICA ES COMPETENCIA EXCLUSIVA DEL "
                "MÉDICO TRATANTE EN EJERCICIO DE SU AUTONOMÍA PROFESIONAL (ART. 17 "
                "LEY 1751/2015), CONSIDERANDO LAS CARACTERÍSTICAS CLÍNICAS DEL "
                "PACIENTE, LA EVIDENCIA CIENTÍFICA Y LAS GPC VIGENTES. LA AUDITORÍA DE "
                "{PAGADOR} NO PUEDE IMPONER CRITERIOS DE ECONOMICIDAD QUE SACRIFIQUEN "
                "LA CALIDAD ASISTENCIAL O LA AUTONOMÍA MÉDICA. EL CRITERIO DE "
                "ECONOMICIDAD NO ES OPONIBLE AL PRESTADOR CUANDO LA DECISIÓN TÉCNICA "
                "ESTÁ MÉDICA Y CIENTÍFICAMENTE JUSTIFICADA." + CIERRE_STD
            ),
        },
        "CL-G10": {
            "titulo": "AUDITOR ADMINISTRATIVO NO IDÓNEO — REQUIERE AUDITOR MÉDICO",
            "texto": (
                ENCABEZADO_STD + "OBJECIÓN FORMULADA POR PERSONAL NO CALIFICADO PARA "
                "EMITIR JUICIO TÉCNICO MÉDICO, DADO QUE EL CUESTIONAMIENTO DE LA "
                "PERTINENCIA CLÍNICA, LA TÉCNICA QUIRÚRGICA, LA DECISIÓN TERAPÉUTICA "
                "O LA APROPIACIÓN DEL APOYO DIAGNÓSTICO ES COMPETENCIA EXCLUSIVA DEL "
                "AUDITOR MÉDICO ESPECIALIZADO EN LA RAMA RESPECTIVA, NO DEL AUDITOR "
                "ADMINISTRATIVO O CONTABLE. CONFORME A LA LEY 1164 DE 2007 (TALENTO "
                "HUMANO EN SALUD), AL CÓDIGO DE ÉTICA MÉDICA (LEY 23 DE 1981) Y AL "
                "ARTÍCULO 17 DE LA LEY 1751 DE 2015, EL ACTO MÉDICO SOLO PUEDE SER "
                "REVISADO Y CONTRADICHO POR OTRO MÉDICO CON FUNDAMENTACIÓN CIENTÍFICA "
                "EXPLÍCITA, BIBLIOGRAFÍA Y CONOCIMIENTO INTEGRAL DEL CASO. LA OBJECIÓN "
                "DEBE SER REVOCADA POR DEFECTO DE COMPETENCIA TÉCNICA." + CIERRE_STD
            ),
        },
    },
}


def render(plantilla, pagador="EL PAGADOR"):
    """
    Sustituye los placeholders en una plantilla por los valores indicados.

    Args:
        plantilla (dict): Plantilla con clave 'texto' (y opcionalmente 'titulo').
        pagador (str): Nombre de la ERP/EPS/IPS pagadora.

    Returns:
        str: Texto renderizado.
    """
    texto = plantilla["texto"]
    return texto.replace("{PAGADOR}", pagador)


def listar_conceptos():
    """Imprime un índice de todos los conceptos disponibles."""
    grupos = {
        "TA": "TARIFAS",
        "SO": "SOPORTES",
        "CO": "COBERTURA",
        "FA": "FACTURACIÓN",
        "CL": "PERTINENCIA CLÍNICA",
    }
    for codigo, nombre in grupos.items():
        print(f"\n=== {nombre} ===")
        for cod_concepto, info in CONCEPTOS_GENERALES[codigo].items():
            print(f"  {cod_concepto}: {info['titulo']}")


def obtener_concepto(codigo):
    """Recupera una plantilla por su código (ej. 'TA-G01', 'CL-G05')."""
    grupo = codigo.split("-")[0]
    return CONCEPTOS_GENERALES[grupo][codigo]


def buscar_por_palabra_clave(palabra):
    """Busca conceptos que contengan una palabra clave en título o texto."""
    resultados = []
    palabra_upper = palabra.upper()
    for grupo, conceptos in CONCEPTOS_GENERALES.items():
        for codigo, info in conceptos.items():
            if palabra_upper in info["titulo"].upper() or palabra_upper in info["texto"].upper():
                resultados.append((codigo, info["titulo"]))
    return resultados


if __name__ == "__main__":
    print(f"Total de conceptos: {sum(len(v) for v in CONCEPTOS_GENERALES.values())}")
    listar_conceptos()
